# -*- coding: utf-8 -*-
"""MacEireann tour-page generator.
Run from the repo root:  python3 tools/gen_tours2.py
Edit the TOURS data below (not the generated .html) and re-run so every
tour page stays consistent. Styling lives in tours/tour.css.
"""
import html
import json

APP_URL = "https://apps.apple.com/app/id6774573617"

APP_BADGE = ('<a class="app-store-btn" href="' + APP_URL + '" aria-label="Download MacEireann on the App Store">'
 '<svg viewBox="0 0 384 512" width="24" height="24" fill="currentColor" aria-hidden="true">'
 '<path d="M318.7 268.7c-.2-36.7 16.4-64.4 50-84.8-18.8-26.9-47.2-41.7-84.7-44.6-35.5-2.8-74.3 20.7-88.5 20.7-15 0-49.4-19.7-76.4-19.7C63.3 141.2 4 184.8 4 273.5q0 39.3 14.4 81.2c12.8 36.7 59 126.7 107.2 125.2 25.2-.6 43-17.9 75.8-17.9 31.8 0 48.3 17.9 76.4 17.9 48.6-.7 90.4-82.5 102.6-119.3-65.2-30.7-61.7-90-61.7-91.9zm-56.6-164.2c27.3-32.4 24.8-61.9 24-72.5-24.1 1.4-52 16.4-67.9 34.9-17.5 19.8-27.8 44.3-25.6 71.9 26.1 2 49.9-11.4 69.5-34.3z"/>'
 '</svg><span class="ass-text"><small>Download on the</small><strong>App Store</strong></span></a>')

def svg(kind):
    s = {
      'dur':'<circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>',
      'dist':'<polygon points="3 11 22 2 13 21 11 13 3 11"></polygon>',
      'dir':'<circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon>',
      'pin':'<circle cx="12" cy="12" r="10"></circle><path d="M2 12h20"></path><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path>',
    }[kind]
    return f'<svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{s}</svg>'

TPL = '''<!DOCTYPE html>
<!--
  MacEireann TOUR PAGE TEMPLATE  (generated by tools/gen_tours2.py)
  To change copy permanently, edit the generator, not this file, so all
  tour pages stay consistent. Styling lives in tour.css.
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <title>{title}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Uncial+Antiqua&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="tour.css">

    <link rel="canonical" href="https://maceireann.ie/tours/{slug}.html">
    <meta name="description" content="{meta}">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#0F291E">

    <meta property="og:title" content="{ogtitle}">
    <meta property="og:description" content="{ogdesc}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://maceireann.ie/tours/{slug}.html">
    <meta property="og:image" content="https://maceireann.ie{ogimg}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:site_name" content="MacÉireann">
    <meta property="og:locale" content="en_IE">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="https://maceireann.ie{ogimg}">

    <link rel="icon" href="/images/logo.png" sizes="32x32" type="image/png">
    <link rel="apple-touch-icon" href="/images/logo.png">

    <script type="application/ld+json">
    {{
      "@context": "https://schema.org",
      "@type": "TouristTrip",
      "name": "{h1} Audio Driving Tour",
      "description": "{meta}",
      "url": "https://maceireann.ie/tours/{slug}.html",
      "image": "https://maceireann.ie{ogimg}",
      "provider": {{ "@type": "Organization", "name": "MacÉireann", "url": "https://maceireann.ie/" }},
      "offers": {{ "@type": "Offer", "url": "{app_url}", "category": "MobileApplication" }},
      "itinerary": {{ "@type": "ItemList", "itemListElement": [{itinerary}] }}
    }}
    </script>
    <script type="application/ld+json">
    {{
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [
        {{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://maceireann.ie/" }},
        {{ "@type": "ListItem", "position": 2, "name": "Tours", "item": "https://maceireann.ie/tours/" }},
        {{ "@type": "ListItem", "position": 3, "name": "{h1}", "item": "https://maceireann.ie/tours/{slug}.html" }}
      ]
    }}
    </script>
{faq_schema}    <script defer src="/analytics.js"></script>
</head>
<body>

    <nav class="tour-nav">
        <a class="brand" href="/">
            <img src="/images/logo.png" alt="MacÉireann logo">
            <span class="brand-name">MacÉireann</span>
        </a>
        {app_badge}
    </nav>

    <header class="tour-hero" style="background-image: url('{img}');">
        <div class="container hero-inner">
            <span class="tour-region">{region}</span>
            <h1>{h1}</h1>
            <p class="tagline">{tagline}</p>
        </div>
    </header>

    <div class="tour-stats">
        <div class="container">
            <div class="tour-stat">{svg_dur}<div><div class="label">Duration</div><div class="value">{dur_v}</div></div></div>
            <div class="tour-stat">{svg_dist}<div><div class="label">Distance</div><div class="value">{dist_v}</div></div></div>
            <div class="tour-stat">{svg_dir}<div><div class="label">Directions</div><div class="value">{dir_v}</div></div></div>
            <div class="tour-stat">{svg_pin}<div><div class="label">Route</div><div class="value">{se_v}</div></div></div>
        </div>
    </div>

    <main class="tour-body">
        <div class="container">
            <p class="breadcrumb"><a href="/">Home</a> &rsaquo; <a href="/tours/">Tours</a> &rsaquo; {h1}</p>

            <p class="lead">{lead}</p>
            <p>{intro}</p>

            <a class="audio-sample" href="{app_url}">
                <span class="play-btn">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><polygon points="6 4 20 12 6 20 6 4"></polygon></svg>
                </span>
                <div>
                    <h4>Hear the full story in the app</h4>
                    <p>Narrated by a traditional storyteller and triggered automatically as you drive. Download on the App Store &rarr;</p>
                </div>
            </a>

            <h2>How to drive it</h2>
            <p>{howto}</p>

            <h2>Stops along the route</h2>
            <p>{stops_intro}</p>
            <ol class="stops">{stops_html}</ol>

            <h2>Available in the app</h2>
            <p>Choose the version that fits your drive &mdash; every tour is GPS-triggered, so the stories play in the right order whichever way you head.</p>
            <div class="variants">{variants_html}</div>
            {variants_note}

{faq_block}            <div class="tour-cta" id="get-the-app">
                <h2>Drive {h1} with its stories</h2>
                <p>MacÉireann is live on the App Store. Download it, choose {h1}, and let a traditional storyteller ride shotgun &mdash; turn by turn, hands on the wheel.</p>
                {app_badge}
                <div class="cta-secondary">
                    <p>Not travelling yet? Get trip-planning tips and new-tour news by email.</p>
                    <form class="waitlist-form" data-source="{slug}">
                        <input type="email" placeholder="Enter your email" required>
                        <button type="submit">Keep Me Posted</button>
                    </form>
                    <p class="signup-msg hidden"></p>
                </div>
            </div>
        </div>
    </main>

    <section class="related">
        <div class="container">
            <h2>More journeys to explore</h2>
            <div class="related-grid">{related_html}</div>
        </div>
    </section>

    <footer>
        <div class="links">
            <a href="/">Home</a>
            <a href="/tours/">All Tours</a>
            <a href="/places/">Places</a>
            <a href="/guides/">Guides</a>
            <a href="/about.html">About</a>
            <a href="/privacy.html">Privacy</a>
            <a href="/support.html">Support</a>
            <a href="#" data-cookie-settings>Cookie settings</a>
        </div>
        <p>© 2026 Yarn Point Tours Ltd. All Rights Reserved.</p>
        <p class="slainte">Sláinte!</p>
    </footer>

    <script src="tour-signup.js"></script>
</body>
</html>
'''

# Stops whose name matches a published /places/ attraction page link down to it.
PLACE_LINKS = {'Cliffs of Moher': 'cliffs-of-moher'}

def stop_title(name):
    esc = html.escape(name)
    slug = PLACE_LINKS.get(name)
    return f'<a href="/places/{slug}.html">{esc}</a>' if slug else esc

def build(t):
    ogimg = '/newimages/og/' + t['slug'] + '-og.jpg'
    faqs = FAQS.get(t['slug'], [])
    if faqs:
        faq_items = ''.join(
            '\n                <div class="faq-item"><h3>' + html.escape(q) + '</h3><p>' + html.escape(a) + '</p></div>'
            for q, a in faqs) + '\n            '
        faq_block = ('            <h2>Common questions</h2>\n            <div class="faq">'
                     + faq_items + '</div>\n\n')
        faq_data = {"@context": "https://schema.org", "@type": "FAQPage",
                    "mainEntity": [{"@type": "Question", "name": q,
                                    "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faqs]}
        faq_schema = '    <script type="application/ld+json">\n    ' + json.dumps(faq_data, ensure_ascii=False) + '\n    </script>\n'
    else:
        faq_block = ''
        faq_schema = ''
    stops_html = ''.join(
        f'\n                <li><h3>{stop_title(s[0])}</h3><p>{html.escape(s[1])}</p></li>'
        for s in t['stops']) + '\n            '
    itinerary = ', '.join(
        f'{{ "@type": "ListItem", "position": {i+1}, "item": {{ "@type": "TouristAttraction", "name": "{s[0].replace(chr(34),chr(39))}" }} }}'
        for i, s in enumerate(t['stops']))
    variants_html = ''.join(
        f'\n                <div class="variant"><h3>{html.escape(n)}</h3><span class="variant-meta">{m}</span></div>'
        for n, m in t['variants']) + '\n            '
    vn = t.get('variants_note', '')
    variants_note = f'<p class="variants-note">{vn}</p>' if vn else ''
    related_html = ''.join(
        f'\n                <a class="related-card" href="/tours/{r[0]}.html" style="background-image:url(\'{r[2]}\');"><span>{r[1]}</span></a>'
        for r in t['related']) + '\n            '
    data = {k: v for k, v in t.items() if k not in ('stops','related','variants','variants_note')}
    out = TPL.format(
        app_url=APP_URL, app_badge=APP_BADGE,
        svg_dur=svg('dur'), svg_dist=svg('dist'), svg_dir=svg('dir'), svg_pin=svg('pin'),
        stops_html=stops_html, itinerary=itinerary,
        variants_html=variants_html, variants_note=variants_note,
        related_html=related_html, ogimg=ogimg, faq_schema=faq_schema, faq_block=faq_block, **data)
    with open(f"tours/{t['slug']}.html", 'w') as f:
        f.write(out)
    print(f"wrote tours/{t['slug']}.html ({len(t['stops'])} stops, {len(t['variants'])} variants)")
# -*- coding: utf-8 -*-

TOURS = [
 {
  'slug':'ring-of-kerry', 'region':'Wild Atlantic Way',
  'title':'Ring of Kerry: Self-Drive Audio Tour, Stops & Map | MacEireann',
  'meta':"Drive the famous Ring of Kerry with an audio guide: wild mountains, ancient stone forts, colourful villages and the islands of the Skellig coast - every stop narrated, Northbound or Southbound.",
  'ogtitle':'Ring of Kerry: Self-Drive Audio Tour, Stops & Map',
  'ogdesc':"One of Ireland's most popular coastal journeys, narrated turn-by-turn. Wild mountains, ancient stones, colourful villages and islands rising from the sea.",
  'img':'/newimages/ringofkerry.webp', 'h1':'Ring of Kerry',
  'tagline':"One of Ireland's most popular coastal journeys - a loop of wild mountains, ancient stones and colourful villages, with the islands of the Skellig coast an optional add-on.",
  'dur_v':'94-180 min','dist_v':'~179 km loop','dir_v':'North & South','se_v':'Kenmare / Killorglin',
  'lead':"The famous Ring of Kerry is a route where landscape and history blend into one. Wild mountains roll down to the sea, ancient ring forts and stone rows stand in green fields, and bright little villages line the road around the Iveragh Peninsula. Travel with me and hear the stories behind it all - ancient legends and real history, woven through with traditional music and interviews with the people who live here.",
  'intro':"This guide covers how to drive the Ring, the stops along the way, and the versions you can choose in the app - including extended tours that add the wild Skellig Ring. Plan your day here for free, then let MacEireann narrate it as you drive, hands on the wheel and eyes on Kerry.",
  'howto':"Most people drive the Ring anti-clockwise from Killarney, but the tour runs the official Wild Atlantic Way arc between Kenmare and Killorglin. In the app, pick Northbound (Kenmare to Killorglin) or Southbound (Killorglin to Kenmare) to match your direction, or the extended versions that loop in the Skellig Ring. The full circuit is a comfortable day with stops, photos and lunch.",
  'stops_intro':"These are the places the tour guides you past, in order. The stories are timed to play as you reach each one.",
  'stops':[
    ('Kenmare','A colourful heritage town at the head of the bay, the southern gateway to the Ring.'),
    ('Dromore','Wooded shores and the romantic ruin of Dromore Castle beside the Kenmare River.'),
    ('Lough Fada','A long, still mountain lake - its name means simply "the long lake" - framed by the Kerry hills.'),
    ('Sneem','A pretty village split by a tumbling river, its houses painted every colour of the rainbow.'),
    ('Ardmore','A sweeping coastal bend with wide views over the water and the mountains beyond.'),
    ("O'Carroll's Cove",'A hidden sandy cove and beach bar tucked just below the road - a perfect pit stop.'),
    ('Derrynane',"Daniel O'Connell's family home above a glorious dune-backed strand, with woodland walks."),
    ('Coomakista Pass','A high, hairpin mountain pass with one of the Ring\'s grandest panoramas over Ballinskelligs Bay.'),
    ('Waterville','The seaside resort Charlie Chaplin loved, looking out across the bay to the islands.'),
    ('Kenneigh','Rolling farmland and quiet boreens on the road toward the Skellig coast.'),
    ('Portmagee Junction','The turning for the Skellig Ring and the brightly painted harbour village of Portmagee.'),
    ('Cahersiveen',"A lively heritage town beneath the old barracks, near the birthplace of Daniel O'Connell."),
    ('Mountain Stage','A Wild Atlantic Way viewpoint clinging to the slopes high above Dingle Bay.'),
    ('Rossbeigh','A long golden spit of beach reaching out into Dingle Bay.'),
    ('Kerry Bog Village','A restored 19th-century bog village, home of the rare Kerry Bog Pony.'),
    ('Killorglin','Famous for August\'s Puck Fair, where a wild mountain goat is crowned king for three days.'),
  ],
  'variants':[
    ('Ring of Kerry - Northbound','~120 min'),
    ('Ring of Kerry - Southbound','~94 min'),
    ('Ring of Kerry + Skellig Ring - Northbound','~180 min'),
    ('Ring of Kerry + Skellig Ring - Southbound','~150 min'),
  ],
  'variants_note':'The extended versions add the quiet, dramatic <a href="/tours/skellig-ring.html">Skellig Ring</a> loop onto the main circuit - perfect if you have the extra time.',
  'related':[('slea-head-drive','Slea Head Drive','/newimages/slea-head.webp'),
             ('skellig-ring','Skellig Ring','/newimages/road-signs.webp'),
             ('cliffs-of-moher-to-galway','Cliffs of Moher to Galway','/newimages/cliffs-of-moher.webp')],
 },
 {
  'slug':'skellig-ring', 'region':'Wild Atlantic Way',
  'title':'Skellig Ring: Audio Tour, Stops & Map (Star Wars Coast) | MacEireann',
  'meta':"Drive the Skellig Ring in County Kerry: dramatic cliffs, remote beaches and beloved fishing ports, with the famous view of Skellig Michael - narrated turn-by-turn in the MacEireann app, Northbound or Southbound.",
  'ogtitle':'Skellig Ring: Audio Tour, Stops & Map (Star Wars Coast)',
  'ogdesc':"A wild looping route of dramatic cliffs, remote beaches and Kerry's best-loved fishing ports, with a storyteller in your pocket.",
  'img':'/newimages/road-signs.webp', 'h1':'Skellig Ring',
  'tagline':"A wild looping route taking in dramatic cliffs, remote beaches and some of County Kerry's best-loved fishing ports.",
  'dur_v':'~40 min','dist_v':'~30 km','dir_v':'North & South','se_v':'Portmagee loop',
  'lead':"The Skellig Ring is the road the tour buses can't take - too narrow for coaches, which keeps it gloriously quiet. It runs out to the most westerly tip of the Iveragh Peninsula, past dramatic cliffs and remote beaches to the harbour villages that launch the boats to Skellig Michael, the island monastery made famous by Star Wars.",
  'intro':"Let me narrate this breathtaking little journey, guided in harmony with the views and carried along by traditional music, tales of old and a pirate story or two. Plan it here for free, then drive it with the app on the road.",
  'howto':"Pick up the Skellig Ring at Portmagee or off the Ring of Kerry near Waterville, and choose the Northbound or Southbound version in the app to suit your direction. The roads are narrow and steep over the Coomanaspic pass - take it slowly and enjoy every turn. It pairs perfectly with the Ring of Kerry for a full day.",
  'stops_intro':"These are the places the tour guides you past, in order. The stories are timed to play as you reach each one.",
  'stops':[
    ('Ballinskelligs','A Gaeltacht village with a Blue Flag beach, a ruined priory and a McCarthy tower house on the strand.'),
    ('Skellig Viewpoint',"The famous telescope view out to Skellig Michael, the monks' rock and a Star Wars filming location."),
    ("St Finian's Bay",'A surf beach in a green bowl of hills, with a chocolate factory looking out over the sand.'),
    ('Coomanaspic Pass','A hair-raising mountain pass with sweeping views over Portmagee, Valentia and the open Atlantic.'),
    ('Kerry Cliffs','Among the highest and most dramatic cliffs in Kerry, with the Skellig Islands framed beyond.'),
    ('Portmagee','A single bright row of houses along the pier, where the Skellig boats and the local trad sessions begin.'),
  ],
  'variants':[
    ('Skellig Ring - Northbound','~40 min'),
    ('Skellig Ring - Southbound','~40 min'),
  ],
  'variants_note':'Driving the full circuit? The Skellig Ring also comes bundled with the <a href="/tours/ring-of-kerry.html">Ring of Kerry</a> in the extended Northbound and Southbound tours.',
  'related':[('ring-of-kerry','Ring of Kerry','/newimages/ringofkerry.webp'),
             ('slea-head-drive','Slea Head Drive','/newimages/slea-head.webp'),
             ('cliffs-of-moher-to-galway','Cliffs of Moher to Galway','/newimages/cliffs-of-moher.webp')],
 },
 {
  'slug':'slea-head-drive', 'region':'Wild Atlantic Way',
  'title':'Slea Head Drive: Dingle Peninsula Audio Tour, Stops & Map | MacEireann',
  'meta':"Drive the Slea Head loop on the Dingle Peninsula: Atlantic cliffs, golden beaches, beehive huts and the Blasket Islands - narrated turn-by-turn in the MacEireann app. Full tour or shorter Fastrack.",
  'ogtitle':'Slea Head Drive: Dingle Peninsula Audio Tour, Stops & Map',
  'ogdesc':"One of Ireland's most breathtaking coastal routes - dramatic cliffs, golden beaches and ancient forts, with a storyteller in your pocket.",
  'img':'/newimages/slea-head.webp', 'h1':'Slea Head Drive',
  'tagline':"One of Ireland's most breathtaking coastal routes, winding west from Dingle past Atlantic cliffs, golden beaches and ancient stone forts.",
  'dur_v':'120-180 min','dist_v':'25-30 km','dir_v':'Full & Fastrack','se_v':'Dingle loop',
  'lead':"The Slea Head Drive winds west from Dingle around the tip of the peninsula, deep in Ireland's Gaeltacht. In a single short loop it takes in dramatic Atlantic cliffs, golden beaches, beehive huts and the Blasket Islands, with Dunmore Head, Brandon Creek and the Gallarus Oratory along the way.",
  'intro':"Join me exploring this Wild Atlantic Way route around the full Slea Head Drive, hearing stories past and present with music and a bit of craic. It's a truly unforgettable tour, taken at your leisure. Plan it here for free, then let the app narrate it as you go.",
  'howto':"Start in Dingle town and follow the loop clockwise via Ventry - the road is narrow and busy in places, so clockwise is the easiest way to follow the loop. Short on time? The app's Fastrack version keeps the headline sights and loops you back to Dingle after the Gallarus Oratory. Bring coins for the small honesty-box attractions along the way.",
  'stops_intro':"These are the places the tour guides you past, in order. The stories are timed to play as you reach each one.",
  'stops':[
    ('Ventry','A sheltered horseshoe of golden sand, and the bay of a great legendary battle.'),
    ('Cahermurphy Beehive Huts','Clusters of dry-stone "clochans," built without mortar over a thousand years ago and still standing.'),
    ('Blasket Islands Viewpoint','The first great view out across the sound to the Great Blasket and its sister islands.'),
    ('Dunmore Head','The most westerly point of mainland Ireland - and a Star Wars filming location.'),
    ('Dunquin Pier',"The zig-zag sheep's-path pier down to the water, one of the most photographed spots in Ireland."),
    ('Blasket Centre','The visitor centre telling the story of the islands and their remarkable writers.'),
    ('Ballyferriter','A Gaeltacht village at the heart of the peninsula\'s Irish-speaking world.'),
    ('Gallarus Oratory','A perfectly preserved early-Christian church, shaped like an upturned boat and watertight after 1,200 years.'),
    ('Murreagh','A quiet stretch of shoreline with views across Smerwick Harbour.'),
    ('Dooneen Pier','A tiny working pier tucked beneath the cliffs.'),
    ('Brandon Creek','The narrow inlet where St Brendan is said to have set sail to discover America.'),
  ],
  'variants':[
    ('Slea Head Drive','~180 min &middot; ~30 km'),
    ('Slea Head Drive Fastrack','~120 min &middot; ~25 km'),
  ],
  'variants_note':'The Fastrack version keeps the highlights and the stories for travellers short on time, looping you back to Dingle after the Gallarus Oratory; the full drive lingers over every cove and clochan.',
  'related':[('ring-of-kerry','Ring of Kerry','/newimages/ringofkerry.webp'),
             ('skellig-ring','Skellig Ring','/newimages/road-signs.webp'),
             ('cliffs-of-moher-to-galway','Cliffs of Moher to Galway','/newimages/cliffs-of-moher.webp')],
 },
 {
  'slug':'cliffs-of-moher-to-galway', 'region':'Wild Atlantic Way',
  'title':'Cliffs of Moher to Galway: Audio Tour Through the Burren | MacEireann',
  'meta':"Drive from the iconic Cliffs of Moher to Galway City along the Wild Atlantic Way: Doolin, the Burren, Ballyvaughan, Kinvara and Clarinbridge - hidden stories and must-see stops narrated turn-by-turn.",
  'ogtitle':'Cliffs of Moher to Galway: Audio Tour Through the Burren',
  'ogdesc':"Travel from the iconic Cliffs of Moher to Galway City, nestled between the Atlantic Ocean and the rolling hills of the Burren.",
  'img':'/newimages/cliffs-of-moher.webp', 'h1':'Cliffs of Moher to Galway',
  'tagline':"Travel from the iconic Cliffs of Moher to the buzz of Galway City - the Wild Atlantic Way at its most spectacular.",
  'dur_v':'~80 min','dist_v':'~90 km','dir_v':'Northbound','se_v':'Cliffs &rarr; Galway',
  'lead':"This drive takes you along the Wild Atlantic Way, nestled between the Atlantic Ocean and the rolling limestone hills of the Burren. Your personal storyteller reveals the hidden stories, the local legends and the must-see stops along the way, from the trad-music village of Doolin to the oyster villages on the shore of Galway Bay.",
  'intro':"Here's how to drive it, the stops worth your time, and the versions you can choose in the app. Plan it for free here, then let MacEireann narrate the whole coast as you go.",
  'howto':"From the Cliffs of Moher visitor centre, head north through Doolin and into <a href=\"/places/the-burren.html\">the Burren</a> on the coast road, then follow the shore of Galway Bay east toward the city. The roads are quiet but narrow across the limestone; take your time. You'll reach Galway in well under two hours of driving, but the stops can easily fill a day. Driving the other way? Use the Southbound version below.",
  'stops_intro':"These are the places the tour guides you past, in order. The stories are timed to play as you reach each one.",
  'stops':[
    ('Cliffs of Moher',"214 metres of sheer Atlantic cliff, with O'Brien's Tower standing on the very brink."),
    ('Doolin','A small village with an outsized reputation - the unofficial capital of Irish traditional music.'),
    ('Ballinalacken Castle','A 15th-century O\'Brien tower house standing on a rocky height above the coast.'),
    ('The Baba Cliffs','Low limestone sea-cliffs where the grey rock of the Burren meets the open Atlantic.'),
    ('Craggagh','A wild, rocky stretch of shore on the western edge of the Burren.'),
    ('Fanore','A rare Blue Flag beach backed by golden dunes, beneath the Burren hills.'),
    ('Murroogh','A quiet coastal townland looking out across Galway Bay to Connemara.'),
    ('Ballyvaughan','A charming little harbour village at the foot of the Burren.'),
    ('The Flaggy Shore',"The limestone shoreline immortalised in Seamus Heaney's poem 'Postscript'."),
    ('Traught Beach','A long sand-and-shingle strand on the southern shore of Galway Bay.'),
    ('Kinvara','A postcard harbour village watched over by Dunguaire Castle.'),
    ('Ballinderreen','A small roadside village on the bay road toward the city.'),
    ('Kilcolgan',"Home of the famous Moran's Oyster Cottage, on the weir."),
    ('Clarinbridge',"Galway's oyster village, host of the long-running Galway Oyster Festival."),
    ('Rinville','Parkland and shoreline on the final approach to Galway city.'),
    ('Galway City',"Journey's end in the Latin Quarter, with buskers, painted shopfronts and the Spanish Arch."),
  ],
  'variants':[
    ('Cliffs of Moher to Galway (Northbound)','~80 min'),
    ('Galway to Cliffs of Moher (Southbound)','~80 min'),
  ],
  'variants_note':'Heading the other way? See the full <a href="/tours/galway-to-cliffs-of-moher.html">Galway to Cliffs of Moher</a> guide.',
  'related':[('galway-to-cliffs-of-moher','Galway to Cliffs of Moher','/newimages/burren.webp'),
             ('ring-of-kerry','Ring of Kerry','/newimages/ringofkerry.webp'),
             ('slea-head-drive','Slea Head Drive','/newimages/slea-head.webp')],
 },
 {
  'slug':'galway-to-cliffs-of-moher', 'region':'Wild Atlantic Way',
  'title':'Galway to Cliffs of Moher: Audio Tour Through the Burren | MacEireann',
  'meta':"Travel from vibrant Galway to the world-famous Cliffs of Moher through the unique landscape of the Burren - locals, history and hidden gems, narrated turn-by-turn in the MacEireann app.",
  'ogtitle':'Galway to Cliffs of Moher: Audio Tour Through the Burren',
  'ogdesc':"From the vibrant city of Galway to the breathtaking heights of the world-famous Cliffs of Moher, through some of Ireland's most spectacular scenery.",
  'img':'/newimages/burren.webp', 'h1':'Galway to Cliffs of Moher',
  'tagline':"Travel with me from the vibrant city of Galway to the breathtaking heights of the world-famous Cliffs of Moher - a journey through some of Ireland's most spectacular scenery.",
  'dur_v':'~80 min','dist_v':'78 km','dir_v':'Southbound','se_v':'Galway &rarr; Cliffs',
  'lead':"From the painted streets of Galway, this drive follows the bay south and west to the breathtaking Cliffs of Moher. Along the way we pass through the unique lunar landscape of the Burren, where rare wildflowers bloom from bare grey rock. Hear from locals, soak up the history and discover the hidden gems - an unforgettable Irish adventure.",
  'intro':"Here's how to drive it, the stops worth stopping for, and the versions you can choose in the app. Plan it for free here, then let MacEireann guide and narrate it on the road.",
  'howto':"Leave Galway south past Clarinbridge and Kinvara, then follow the coast into <a href=\"/places/the-burren.html\">the Burren</a> before reaching Doolin and the cliffs. It's a short drive, so build in plenty of time to wander the limestone and the harbour villages. Coming from the cliffs instead? Use the Northbound version below.",
  'stops_intro':"These are the places the tour guides you past, in order. The stories are timed to play as you reach each one.",
  'stops':[
    ('Galway City',"Start in the City of the Tribes - medieval streets, the river Corrib and the legend behind Lynch's Window."),
    ('Rinville','Parkland and shoreline on the edge of the city, looking out over Galway Bay.'),
    ('Clarinbridge',"Galway's oyster village, host of the long-running Galway Oyster Festival."),
    ('Kilcolgan',"Home of the famous Moran's Oyster Cottage, on the weir."),
    ('Ballinderreen','A small roadside village on the bay road south.'),
    ('Kinvara','A postcard harbour village watched over by Dunguaire Castle.'),
    ('Traught Beach','A long sand-and-shingle strand on the southern shore of Galway Bay.'),
    ('The Flaggy Shore',"The limestone shoreline immortalised in Seamus Heaney's poem 'Postscript'."),
    ('Ballyvaughan','A charming little harbour village at the foot of the Burren.'),
    ('Murroogh','A quiet coastal townland looking out across Galway Bay.'),
    ('Fanore','A rare Blue Flag beach backed by golden dunes, beneath the Burren hills.'),
    ('Ballinalacken Castle','A 15th-century O\'Brien tower house standing on a rocky height above the coast.'),
    ('Doolin','The trad-music village where the cliff walk begins and the Aran ferries depart.'),
    ('Cliffs of Moher','The grand finale - 214 metres of cliff and the wide Atlantic, best saved for last.'),
  ],
  'variants':[
    ('Galway to Cliffs of Moher (Southbound)','~80 min &middot; 78 km'),
    ('Cliffs of Moher to Galway (Northbound)','~80 min'),
  ],
  'variants_note':'Heading the other way? See the full <a href="/tours/cliffs-of-moher-to-galway.html">Cliffs of Moher to Galway</a> guide.',
  'related':[('cliffs-of-moher-to-galway','Cliffs of Moher to Galway','/newimages/cliffs-of-moher.webp'),
             ('ring-of-kerry','Ring of Kerry','/newimages/ringofkerry.webp'),
             ('slea-head-drive','Slea Head Drive','/newimages/slea-head.webp')],
 },
 {
  'slug':'dublin-to-galway', 'region':'Leinster &middot; Connacht',
  'title':'Dublin to Galway: Cross-Ireland Audio Road Trip & Stops | MacEireann',
  'meta':"Drive coast to coast from Dublin to Galway with an audio guide: a trip through Ireland's past, from Vikings to medieval power struggles to the wonder of the West. Don't just drive it - discover it.",
  'ogtitle':'Dublin to Galway: Cross-Ireland Audio Road Trip & Stops',
  'ogdesc':"A long stretch of motorway from East to West, turned into a trip through Ireland's past - with a traditional storyteller in your pocket.",
  'img':'/images/image7.jpg', 'h1':'Dublin to Galway',
  'tagline':"A long stretch of motorway from East to West - and a journey through Ireland's past, from Vikings to medieval power struggles and the wonder of the West.",
  'dur_v':'~120 min','dist_v':'191 km','dir_v':'One-way','se_v':'Dublin &rarr; Galway',
  'lead':"Most people cross Ireland on the motorway in a flat two hours, the middle of the country a green blur out the window. They miss it entirely - because the midlands are where Ireland kept its memory. Join me for a trip through Ireland's past, from the Viking city of Dublin, across the royal plains and contested castles of the midlands, over the mighty Shannon and on into the West. Don't just drive it - discover it.",
  'intro':"This guide covers the coast-to-coast drive and the stories that unfold county by county as you cross the country. Plan it here for free, then let MacEireann narrate the whole crossing - ideal for the drive west on the day you land.",
  'howto':"The fast route is the M4/M6 motorway, roughly two hours non-stop from Dublin to Galway. The tour follows the corridor and triggers each chapter of the story as you cross from county to county, so there's nothing to plan and nowhere you have to stop - just drive, listen and watch Ireland change around you.",
  'stops_intro':"This is a coast-to-coast drive, so the tour is told region by region as you cross the country. Here's the journey in order.",
  'stops':[
    ('Dublin','The capital and Viking city on the Liffey, where the great road west begins.'),
    ('Kildare','The wide plains of the Curragh - Ireland\'s horse country and ancient common grazing land.'),
    ('Meath & Westmeath','The royal midlands, dotted with the castles, lakes and crannogs of the old Gaelic lords.'),
    ('Athlone','The crossing of the mighty Shannon, guarded by its castle - and Sean\'s Bar, said to be the oldest pub in Ireland.'),
    ('Roscommon','Lake-and-pasture country, the old heartland of the kings of Connacht.'),
    ('County Galway','Into the West at last, where the midlands give way to stone walls, bog and big Atlantic skies.'),
    ('Galway City',"Journey's end on the Atlantic - the City of the Tribes, with its painted streets and the Spanish Arch."),
  ],
  'variants':[
    ('Dublin to Galway','~120 min &middot; 191 km'),
  ],
  'variants_note':'Arriving into Dublin and heading for the west coast? This is the perfect tour for your first drive across the country.',
  'related':[('galway-to-cliffs-of-moher','Galway to Cliffs of Moher','/newimages/burren.webp'),
             ('cliffs-of-moher-to-galway','Cliffs of Moher to Galway','/newimages/cliffs-of-moher.webp'),
             ('ring-of-kerry','Ring of Kerry','/newimages/ringofkerry.webp')],
 },
]

FAQS = {'ring-of-kerry': [('How long does it take to drive the Ring of Kerry?', 'Non-stop the loop takes about 3.5 to 4 hours, but with photo stops, short walks and lunch most people make a full day of it (6 to 8 hours). The MacEireann audio tour runs from 94 to 180 minutes depending on the version you choose.'), ('Which direction should I drive the Ring of Kerry?', 'Locals and tour coaches drive it anti-clockwise (Killarney to Killorglin to Waterville to Kenmare), and it is best to follow them so you are not meeting big buses head-on on the narrow stretches. In the app you can pick the Northbound or Southbound version to match your direction.'), ('When is the best time of year to drive the Ring of Kerry?', 'May to September gives the best weather and the longest daylight. Setting off early in the morning helps you stay ahead of the tour buses.'), ('Do I need a phone signal for the audio tour?', "No. Download the tour before you set off and it uses your phone's GPS to trigger each story, so it keeps working even on the stretches with no mobile coverage.")], 'skellig-ring': [('How long does the Skellig Ring take to drive?', 'The Skellig Ring is a short loop of about 30 km and the audio tour runs around 40 minutes, though you will want longer to stop at the cliffs and viewpoints. It pairs perfectly with the Ring of Kerry for a full day.'), ('Can you see Skellig Michael from the Skellig Ring?', 'Yes. There are several viewpoints, including the famous telescope point, looking out to Skellig Michael, the island monastery from Star Wars. Landing on the island itself needs a separate, pre-booked boat from Portmagee.'), ('Is the Skellig Ring suitable for campervans and larger vehicles?', 'The roads are narrow and steep over the Coomanaspic pass, which is why tour coaches cannot use it. Cars and campervans are fine if you take it slowly and with care.'), ('Do I need a phone signal for the audio tour?', "No. Download the tour first and it runs on your phone's GPS, so it works even where there is no mobile coverage.")], 'slea-head-drive': [('How long does the Slea Head Drive take?', 'The loop is short in distance (about 30 km) but packed with stops. The full audio tour runs about 180 minutes, or roughly 120 minutes for the Fastrack version, so allow at least half a day.'), ('What is the difference between the full tour and the Fastrack version?', 'The full Slea Head Drive covers every cove, fort and beehive hut, while the Fastrack version keeps the headline sights and loops you back to Dingle after the Gallarus Oratory - ideal if you are short on time.'), ('Which direction should I drive Slea Head?', 'Drive clockwise from Dingle via Ventry. The road is narrow and busy in places, so clockwise is the easiest way to follow the loop.'), ('Do I need a phone signal for the audio tour?', "No. Download the tour before you set off and it uses your phone's GPS to play each story automatically, even where there is no mobile coverage.")], 'cliffs-of-moher-to-galway': [('How long does it take to drive from the Cliffs of Moher to Galway?', 'About 1.5 to 2 hours non-stop, but with the Burren, Doolin and the bayside villages it easily fills a day. The audio tour itself runs around 80 minutes.'), ('What is the best route from the Cliffs of Moher to Galway?', 'The scenic coastal route through Doolin, the Burren and Ballyvaughan, then along the shore of Galway Bay - not the faster inland road. The tour follows this scenic way.'), ('Can I do this drive in the other direction?', 'Yes. There is a separate Galway to Cliffs of Moher (Southbound) version of the tour.'), ('Do I need a phone signal for the audio tour?', "No. Download the tour first and it uses your phone's GPS to trigger each story, so it works even on stretches with no mobile coverage.")], 'galway-to-cliffs-of-moher': [('How long does it take to drive from Galway to the Cliffs of Moher?', 'Roughly 1.5 hours non-stop (about 78 km via the coast), but allow a half to full day to enjoy the Burren and the villages. The audio tour runs around 80 minutes.'), ('Should I take the coastal route or the direct road?', 'The coastal route through Kinvara and the Burren is far more scenic and is the one the tour follows. The direct inland road is faster but misses the highlights.'), ('Can I drive it the other way?', 'Yes. There is a Cliffs of Moher to Galway (Northbound) version of the tour as well.'), ('Do I need a phone signal for the audio tour?', "No. Download the tour before you travel and it runs on your phone's GPS, working even where there is no mobile coverage.")], 'dublin-to-galway': [('How long does it take to drive from Dublin to Galway?', 'About 2 to 2.5 hours non-stop on the M4/M6 motorway (around 190 km). The audio tour runs about 120 minutes and is timed to the motorway drive.'), ('Is there much to see between Dublin and Galway?', 'More than most people realise - the plains of Kildare, the royal midlands, the Shannon crossing at Athlone with its ancient pub, and on into Connacht. The tour tells the story county by county as you cross the country.'), ('Do I need to stop anywhere along the way?', 'No. The tour is designed for the motorway drive with no detours required, though Athlone makes a great break if you have the time.'), ('Do I need a phone signal for the audio tour?', "No. Download the tour before you set off and it uses your phone's GPS to play each chapter automatically, even where coverage is patchy.")]}

for t in TOURS:
    build(t)
