# -*- coding: utf-8 -*-
"""MacEireann trip-planning guide generator.
Run from the repo root:  python3 tools/gen_guides.py
Edit the GUIDES data below (not the generated .html) and re-run so every
guide stays consistent. Styling lives in tours/tour.css.
Sibling of tools/gen_tours2.py and tools/gen_places.py — same look,
long-form article page type with Article + FAQPage schema.
"""
import html
import json

APP_URL = "https://apps.apple.com/app/id6774573617"

APP_BADGE = ('<a class="app-store-btn" href="' + APP_URL + '" aria-label="Download MacEireann on the App Store">'
 '<svg viewBox="0 0 384 512" width="24" height="24" fill="currentColor" aria-hidden="true">'
 '<path d="M318.7 268.7c-.2-36.7 16.4-64.4 50-84.8-18.8-26.9-47.2-41.7-84.7-44.6-35.5-2.8-74.3 20.7-88.5 20.7-15 0-49.4-19.7-76.4-19.7C63.3 141.2 4 184.8 4 273.5q0 39.3 14.4 81.2c12.8 36.7 59 126.7 107.2 125.2 25.2-.6 43-17.9 75.8-17.9 31.8 0 48.3 17.9 76.4 17.9 48.6-.7 90.4-82.5 102.6-119.3-65.2-30.7-61.7-90-61.7-91.9zm-56.6-164.2c27.3-32.4 24.8-61.9 24-72.5-24.1 1.4-52 16.4-67.9 34.9-17.5 19.8-27.8 44.3-25.6 71.9 26.1 2 49.9-11.4 69.5-34.3z"/>'
 '</svg><span class="ass-text"><small>Download on the</small><strong>App Store</strong></span></a>')

MID_CTA = ('''            <a class="audio-sample" href="''' + APP_URL + '''">
                <span class="play-btn">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><polygon points="6 4 20 12 6 20 6 4"></polygon></svg>
                </span>
                <div>
                    <h4>Don't just drive it &mdash; discover it</h4>
                    <p>MacÉireann narrates the legends and history of the road as you reach each place, automatically and offline. Download on the App Store &rarr;</p>
                </div>
            </a>''')

TPL = '''<!DOCTYPE html>
<!--
  MacEireann TRIP-PLANNING GUIDE  (generated by tools/gen_guides.py)
  To change copy permanently, edit the generator, not this file, so all
  guides stay consistent. Styling lives in /tours/tour.css.
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <title>{title}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Uncial+Antiqua&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/tours/tour.css">

    <link rel="canonical" href="https://maceireann.ie/guides/{slug}.html">
    <meta name="description" content="{meta}">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#0F291E">

    <meta property="og:title" content="{ogtitle}">
    <meta property="og:description" content="{ogdesc}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://maceireann.ie/guides/{slug}.html">
    <meta property="og:image" content="https://maceireann.ie{ogimg}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:site_name" content="MacÉireann">
    <meta property="og:locale" content="en_IE">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="https://maceireann.ie{ogimg}">

    <link rel="icon" href="/images/logo.png" sizes="32x32" type="image/png">
    <link rel="apple-touch-icon" href="/images/logo.png">

    <script type="application/ld+json">
    {{
      "@context": "https://schema.org",
      "@type": "Article",
      "headline": "{h1}",
      "description": "{meta}",
      "image": "https://maceireann.ie{ogimg}",
      "author": {{ "@type": "Organization", "name": "MacÉireann", "url": "https://maceireann.ie/" }},
      "publisher": {{ "@type": "Organization", "name": "MacÉireann", "logo": {{ "@type": "ImageObject", "url": "https://maceireann.ie/images/logo.png" }} }},
      "datePublished": "{published}",
      "dateModified": "{modified}",
      "mainEntityOfPage": "https://maceireann.ie/guides/{slug}.html"
    }}
    </script>
    <script type="application/ld+json">
    {{
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [
        {{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://maceireann.ie/" }},
        {{ "@type": "ListItem", "position": 2, "name": "Guides", "item": "https://maceireann.ie/guides/" }},
        {{ "@type": "ListItem", "position": 3, "name": "{crumb}", "item": "https://maceireann.ie/guides/{slug}.html" }}
      ]
    }}
    </script>
{faq_schema}    <script defer src="/analytics.js"></script>
</head>
<body>

    <nav class="tour-nav">
        <a class="brand" href="/">
            <img src="/images/logo.png" alt="MacÉireann logo">
            <span class="brand-name">MacÉireann</span>
        </a>
        {app_badge}
    </nav>

    <header class="tour-hero" style="background-image: url('{img}');">
        <div class="container hero-inner">
            <span class="tour-region">{region}</span>
            <h1>{h1}</h1>
            <p class="tagline">{tagline}</p>
        </div>
    </header>

    <main class="tour-body">
        <div class="container">
            <p class="breadcrumb"><a href="/">Home</a> &rsaquo; <a href="/guides/">Guides</a> &rsaquo; {crumb}</p>

{body}

{faq_block}            <div class="tour-cta" id="get-the-app">
                <h2>{cta_h2}</h2>
                <p>{cta_p}</p>
                {app_badge}
                <div class="cta-secondary">
                    <p>Not travelling yet? Get trip-planning tips and new-tour news by email.</p>
                    <form class="waitlist-form" data-source="guide-{slug}">
                        <input type="email" placeholder="Enter your email" required>
                        <button type="submit">Keep Me Posted</button>
                    </form>
                    <p class="signup-msg hidden"></p>
                </div>
            </div>
        </div>
    </main>

    <section class="related">
        <div class="container">
            <h2>Start planning your drive</h2>
            <div class="related-grid">{related_html}</div>
        </div>
    </section>

    <footer>
        <div class="links">
            <a href="/">Home</a>
            <a href="/tours/">All Tours</a>
            <a href="/places/">Places</a>
            <a href="/guides/">Guides</a>
            <a href="/about.html">About</a>
            <a href="/privacy.html">Privacy</a>
            <a href="/support.html">Support</a>
            <a href="#" data-cookie-settings>Cookie settings</a>
        </div>
        <p>© 2026 Yarn Point Tours Ltd. All Rights Reserved.</p>
        <p class="slainte">Sláinte!</p>
    </footer>

    <script src="/tours/tour-signup.js"></script>
</body>
</html>
'''


def build(g):
    ogimg = '/newimages/og/' + g['slug'] + '-og.jpg'
    related_html = ''.join(
        f'\n                <a class="related-card" href="{r[0]}" style="background-image:url(\'{r[2]}\');"><span>{r[1]}</span></a>'
        for r in g['related']) + '\n            '
    faqs = g.get('faqs', [])
    if faqs:
        faq_items = ''.join(
            '\n                <div class="faq-item"><h3>' + html.escape(q) + '</h3><p>' + html.escape(a) + '</p></div>'
            for q, a in faqs) + '\n            '
        faq_block = ('            <h2>Frequently asked questions</h2>\n            <div class="faq">'
                     + faq_items + '</div>\n\n')
        faq_data = {"@context": "https://schema.org", "@type": "FAQPage",
                    "mainEntity": [{"@type": "Question", "name": q,
                                    "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faqs]}
        faq_schema = '    <script type="application/ld+json">\n    ' + json.dumps(faq_data, ensure_ascii=False) + '\n    </script>\n'
    else:
        faq_block = ''
        faq_schema = ''
    data = {k: v for k, v in g.items() if k not in ('related', 'faqs')}
    out = TPL.format(app_url=APP_URL, app_badge=APP_BADGE, ogimg=ogimg,
                     related_html=related_html, faq_block=faq_block, faq_schema=faq_schema, **data)
    with open(f"guides/{g['slug']}.html", 'w') as f:
        f.write(out)
    print(f"wrote guides/{g['slug']}.html ({len(faqs)} FAQs)")


WAW_BODY = '''            <p class="lead">The Wild Atlantic Way is the longest defined coastal touring route in the world &mdash; some 2,500 kilometres (1,550 miles) of cliffs, beaches, peninsulas and harbour towns running down the entire western seaboard of Ireland. This guide explains how to drive it: how long you need, where to start, the route region by region, a ready-made 7-day itinerary, and the practical tips that make the difference between a good road trip and a great one.</p>

            <p>It runs from the Inishowen Peninsula and Malin Head in County Donegal, at the very north, all the way to the harbour town of Kinsale in County Cork, in the south, threading through nine counties along the way. You don't have to drive all of it &mdash; almost nobody does in one trip &mdash; but knowing how the whole route fits together is the key to choosing the right stretch for the time you have.</p>

            <h2>The Wild Atlantic Way at a glance</h2>
            <div class="glance">
                <div class="glance-item"><div class="glance-num">2,500 km</div><div class="glance-label">World's longest defined coastal route</div></div>
                <div class="glance-item"><div class="glance-num">9 counties</div><div class="glance-label">From Donegal down to Cork</div></div>
                <div class="glance-item"><div class="glance-num">10&ndash;14 days</div><div class="glance-label">To drive the whole route with stops</div></div>
                <div class="glance-item"><div class="glance-num">4&ndash;7 days</div><div class="glance-label">For the iconic southwest alone</div></div>
            </div>
            <p style="font-size:0.95rem; color:#6b766f;">It runs from Malin Head in County Donegal to Kinsale in County Cork &mdash; just follow the blue zig-zag Wild Atlantic Way signs and the brown <em>Discovery Point</em> markers the whole way down.</p>

            <h2>How many days do you need?</h2>
            <p>The honest answer: as many as you can give it. Driving the full route end to end, with stops, is a two-week trip. But the Wild Atlantic Way divides neatly into regions, and the most spectacular of them &mdash; the southwest, where Clare, Galway and Kerry meet the ocean &mdash; can be done justice in well under a week. Here's how the time tends to break down:</p>

            <div class="option-cards">
                <div class="option-card"><div class="oc-eyebrow">Long weekend</div><h3>3&ndash;4 days</h3><p>One region in depth &mdash; the Clare coast and Galway, or the Kerry peninsulas.</p></div>
                <div class="option-card"><div class="oc-eyebrow">The sweet spot</div><h3>One week</h3><p>The full southwest: Galway &rarr; the Burren &rarr; the Cliffs of Moher &rarr; Dingle &rarr; the Ring of Kerry.</p></div>
                <div class="option-card"><div class="oc-eyebrow">The full thing</div><h3>10&ndash;14 days</h3><p>The whole route, north to south, at a pace that lets you actually stop.</p></div>
            </div>

            <p>If this is your first time, resist the urge to drive the lot. The roads are slower than the map suggests, and the joy of the west coast is in the stopping &mdash; the beach you didn't plan on, the harbour pub, the headland you climb just to see what's beyond it.</p>

            <h2>Which direction, and where to start</h2>
            <p>Most people drive the Wild Atlantic Way from north to south, chasing the sun down the coast, but there's no wrong way round &mdash; and most visitors drive just a section rather than the whole thing. The single most common starting point isn't on the route at all: it's Dublin, where most travellers land. From there it's a straightforward run west to Galway to join the coast &mdash; a drive we've turned into a tour in its own right, <a href="/tours/dublin-to-galway.html">Dublin to Galway</a>, so the crossing of Ireland's midlands becomes part of the story rather than dead motorway time.</p>
            <p>One thing to settle before you set off: in Ireland you <a href="/guides/driving-in-ireland.html">drive on the left</a>, and the coastal roads are narrow, winding and often single-track with passing places. If you're not used to it, give yourself an easy first day and take the lanes slowly &mdash; our <a href="/guides/driving-in-ireland.html">guide to driving in Ireland</a> covers the rest. It quickly becomes second nature.</p>

''' + MID_CTA + '''

            <h2>The route, region by region</h2>
            <p>From north to south, the Wild Atlantic Way falls into a handful of distinct stretches, each with its own character.</p>

            <h3>The Northern Headlands &mdash; Donegal, Sligo &amp; Mayo</h3>
            <p>The wild, less-travelled top of the route: the sea cliffs of Slieve League (among the highest in Europe), the surf town of Bundoran, the blow-hole at Downpatrick Head and the long Atlantic-battered roads of Achill Island. This is the Wild Atlantic Way at its rawest and emptiest &mdash; magnificent if you have the days, and easily a trip of its own.</p>

            <h3>The West &mdash; Galway &amp; Connemara</h3>
            <p>Galway city is the buzzing heart of the west coast: painted shopfronts, trad sessions spilling out of pubs, and the Spanish Arch on the river. West of it lies Connemara, a land of bog, mountain and island. Galway also makes the perfect hinge for the southwest &mdash; the point where most one-week trips really begin.</p>

            <h3>The heart of the route &mdash; County Clare</h3>
            <p>If you only drive one stretch, make it this one. South of Galway Bay the coast runs into the <a href="/places/the-burren.html">Burren</a>, a vast pavement of bare limestone where Arctic and Mediterranean wildflowers bloom side by side from the rock, and on to the <a href="/places/cliffs-of-moher.html">Cliffs of Moher</a>, 214 metres of sheer Atlantic cliff and Ireland's most visited natural wonder. We've narrated this coast in both directions &mdash; <a href="/tours/galway-to-cliffs-of-moher.html">Galway to the Cliffs of Moher</a> and <a href="/tours/cliffs-of-moher-to-galway.html">Cliffs of Moher to Galway</a> &mdash; through Doolin, Ballyvaughan and the oyster villages of the bay.</p>

            <h3>The grand finale &mdash; County Kerry</h3>
            <p>Kerry is where the Wild Atlantic Way reaches its climax, on three great peninsulas reaching into the ocean. The <a href="/tours/ring-of-kerry.html">Ring of Kerry</a> loops the Iveragh Peninsula past mountains, ancient stone forts and colourful villages. To the north, the <a href="/tours/slea-head-drive.html">Slea Head Drive</a> rounds the tip of the Dingle Peninsula past beehive huts, golden strands and the Blasket Islands. And tucked off the Ring is the quiet, dramatic <a href="/tours/skellig-ring.html">Skellig Ring</a>, with its view out to the monastery island of Skellig Michael. Each is a full day, and together they're the reason many people come at all. Torn between the first two? See <a href="/guides/ring-of-kerry-vs-dingle.html">Ring of Kerry vs Dingle</a>, or browse them all on the <a href="/tours/">tours page</a>.</p>

            <h3>The southern finish &mdash; West Cork</h3>
            <p>The route mellows as it runs into West Cork, past the Beara Peninsula and the brightly painted villages of Allihies and Eyeries to its official end at Kinsale, a foodie harbour town that's a fitting place to raise a final glass.</p>

            <h2>A 7-day Wild Atlantic Way itinerary</h2>
            <p>This week-long route covers the very best of the coast &mdash; the Clare, Galway and Kerry sections &mdash; starting from Dublin, where most travellers arrive. Every driving day below has a MacÉireann audio tour to narrate it. Prefer a whole-Ireland loop that takes in the historic south too? See our <a href="/guides/7-day-ireland-itinerary.html">7-day Ireland road trip itinerary</a>.</p>

            <p class="guide-day"><span class="day-label">Day 1</span>Dublin to Galway</p>
            <p>Pick up your hire car and cross the country to the west coast, letting the <a href="/tours/dublin-to-galway.html">Dublin to Galway</a> tour turn the midlands into a story of Vikings, castles and the mighty Shannon. Overnight in Galway.</p>

            <p class="guide-day"><span class="day-label">Day 2</span>Galway, the Burren &amp; the Cliffs of Moher</p>
            <p>Follow the coast south with the <a href="/tours/galway-to-cliffs-of-moher.html">Galway to Cliffs of Moher</a> tour, through the lunar <a href="/places/the-burren.html">Burren</a> to the <a href="/places/cliffs-of-moher.html">Cliffs of Moher</a>. Time your arrival at the cliffs for late afternoon, when the coaches have gone.</p>

            <p class="guide-day"><span class="day-label">Day 3</span>Into Kerry</p>
            <p>Drive south from Clare toward the Kerry peninsulas (via the Tarbert&ndash;Killimer car ferry across the Shannon estuary). Settle in around Dingle or Killarney for the next three nights.</p>

            <p class="guide-day"><span class="day-label">Day 4</span>The Slea Head Drive</p>
            <p>Loop the tip of the Dingle Peninsula on the <a href="/tours/slea-head-drive.html">Slea Head Drive</a> &mdash; beehive huts, ancient oratories and the Blasket Islands &mdash; one of the most beautiful short drives in Ireland.</p>

            <p class="guide-day"><span class="day-label">Day 5</span>The Ring of Kerry</p>
            <p>Give a full day to the <a href="/tours/ring-of-kerry.html">Ring of Kerry</a>, the famous loop of the Iveragh Peninsula. Set off early to stay ahead of the tour buses.</p>

            <p class="guide-day"><span class="day-label">Day 6</span>The Skellig Ring</p>
            <p>Add the quieter <a href="/tours/skellig-ring.html">Skellig Ring</a>, too narrow for coaches, for cliffs, remote beaches and the view out to Skellig Michael. Overnight in Kenmare.</p>

            <p class="guide-day"><span class="day-label">Day 7</span>Kenmare to Cork</p>
            <p>Wind down through West Cork toward Kinsale and the route's southern end &mdash; or turn back for Dublin, full of stories.</p>

            <h2>Practical tips for driving the Wild Atlantic Way</h2>
            <ul style="font-size:1.08rem; color:#3a463f; margin:0 0 18px 22px; line-height:1.7;">
                <li><strong>Hire a car you're comfortable in.</strong> Most hire cars in Ireland are manual; book an automatic well ahead if you need one, and consider a smaller car for the narrow lanes.</li>
                <li><strong>Drive on the left,</strong> and take single-track roads slowly &mdash; pull into passing places to let oncoming traffic and locals through.</li>
                <li><strong>Allow more time than the map says.</strong> Coastal roads are slow, and you'll want to stop far more than you expect.</li>
                <li><strong>Fuel up in towns.</strong> Petrol stations thin out on the remote stretches and peninsulas.</li>
                <li><strong>Pack for four seasons in a day.</strong> The Atlantic weather is changeable; layers and a waterproof are essential year-round.</li>
                <li><strong>Book accommodation ahead</strong> in July and August, when the popular towns fill up.</li>
                <li><strong>Bring the stories with you.</strong> Download your MacÉireann tours before you set off &mdash; they run on GPS and work offline, exactly where the coast has no signal.</li>
            </ul>

            <h2>When is the best time to drive it?</h2>
            <p>May to September gives the best weather and the longest days &mdash; in June the light lasts until nearly 11pm, which buys you hours of extra driving and exploring. May and September are the sweet spot: warm-ish, quieter, and easier for last-minute beds. The route is open year-round and winter brings wild, empty drama to the coast, but expect short days and some seasonal closures. Whenever you go, set off early to have the famous spots to yourself before the day-trippers arrive. For the full season-by-season picture, see our guide to <a href="/guides/best-time-to-visit-ireland.html">the best time to visit Ireland</a>.</p>
'''

DRIVING_BODY = '''            <p class="lead">A car is the best way to see Ireland &mdash; it unlocks the empty coast roads, the villages off the tour-bus routes and the freedom to stop wherever the view takes you. But a few things catch first-time visitors out, starting with the small matter of which side of the road to drive on. Here's everything you need to drive in Ireland with confidence.</p>

            <h2>The essentials at a glance</h2>
            <div class="glance">
                <div class="glance-item"><div class="glance-num">On the left</div><div class="glance-label">Which side of the road you drive on</div></div>
                <div class="glance-item"><div class="glance-num">km/h</div><div class="glance-label">Speed limits are metric, not mph</div></div>
                <div class="glance-item"><div class="glance-num">Mostly manual</div><div class="glance-label">Book an automatic well in advance</div></div>
                <div class="glance-item"><div class="glance-num">Mid-20s+</div><div class="glance-label">Typical minimum age to hire a car</div></div>
            </div>

            <h2>Driving on the left</h2>
            <p>The single biggest adjustment: in Ireland you drive on the <strong>left</strong>, the driver sits on the right of the car, and you overtake on the right. A handy reminder is that the driver should always be nearest the centre line of the road. The trickiest moments come just after you've stopped &mdash; pulling out of a car park or a petrol station &mdash; so pause and picture it before you set off. Give yourself an easy first drive on quieter roads, and it becomes second nature within a day.</p>

            <h2>Hiring a car</h2>
            <p>Most hire cars in Ireland are manual (stick shift). Automatics exist but are fewer and pricier, so book one well ahead if you can't drive a manual. A smaller car is a genuine advantage on narrow rural lanes and in tight village car parks. When you book, check the excess (the amount you'd pay if the car is damaged) and how much it costs to reduce it &mdash; and note that Ireland is sometimes excluded from the car-hire insurance that comes with credit cards, so confirm your cover rather than assume it. Most companies rent to drivers from their mid-twenties upward, with surcharges or restrictions for the very young or older drivers, so check the age policy when you book.</p>

''' + MID_CTA + '''

            <h2>Know your roads</h2>
            <p>Irish roads come in a few flavours, and the letter on the road number tells you what to expect:</p>
            <div class="option-cards">
                <div class="option-card"><div class="oc-eyebrow">Motorway</div><h3>M roads</h3><p>Fast dual carriageways linking the cities &mdash; the easiest driving in the country, with a few tolls.</p></div>
                <div class="option-card"><div class="oc-eyebrow">National</div><h3>N roads</h3><p>The main cross-country routes: mostly good single carriageway that dips through the odd town.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Regional &amp; local</div><h3>R &amp; L roads</h3><p>The scenic stuff &mdash; narrow, winding, sometimes single-track with grass up the middle. Slow right down.</p></div>
            </div>
            <p>The <a href="/guides/wild-atlantic-way.html">Wild Atlantic Way</a> and most of the best coastal drives run on R and L roads, which is exactly why they're so beautiful &mdash; and why you should always allow far more time than the distance suggests. On single-track lanes, use the passing places: pull in (or reverse to the nearest one) to let oncoming cars and locals through, and give the customary one-finger-off-the-wheel wave of thanks.</p>

            <h2>Speed limits</h2>
            <p>Limits are in kilometres per hour, shown on round white signs with a red border. They were updated in 2025, so even returning visitors should note the current defaults:</p>
            <table class="guide-table">
                <thead><tr><th>Road type</th><th>Speed limit</th></tr></thead>
                <tbody>
                    <tr><td>Motorway (M)</td><td>120 km/h</td></tr>
                    <tr><td>National road (N)</td><td>100 km/h</td></tr>
                    <tr><td>Regional road (R)</td><td>80 km/h</td></tr>
                    <tr><td>Local road (L)</td><td>60 km/h</td></tr>
                    <tr><td>Towns &amp; built-up areas</td><td>50 km/h (often 30 in centres)</td></tr>
                </tbody>
            </table>
            <p>On a narrow rural lane these are an upper limit, not a target &mdash; your safe, comfortable speed will usually be a good deal lower.</p>

            <h2>Tolls</h2>
            <p>A handful of motorways have tolls, paid at barrier plazas by cash or card. The exception is Dublin's <strong>M50</strong> ring road, which is barrier-free: cameras read your number plate and you must pay online (via eFlow) by 8pm the following day. Hire companies usually have an arrangement for this, but confirm it so you don't pick up a penalty.</p>

            <h2>Fuel</h2>
            <p>Know whether your car takes petrol or diesel before you fill up &mdash; diesel is very common in hire cars, and putting in the wrong fuel is an expensive mistake. Fill up in towns; stations thin out on the remote peninsulas and can keep shorter hours on Sundays.</p>

            <h2>Rules &amp; etiquette</h2>
            <ul style="font-size:1.08rem; color:#3a463f; margin:0 0 18px 22px; line-height:1.7;">
                <li><strong>Seatbelts are compulsory</strong> for everyone in the car; small children need an appropriate booster or seat.</li>
                <li><strong>Roundabouts run clockwise</strong> &mdash; give way to traffic coming from your right.</li>
                <li><strong>Phones must be hands-free.</strong> Handling a phone while driving carries heavy penalties.</li>
                <li><strong>Drink-driving limits are low and strictly enforced.</strong> The safe approach is simply not to.</li>
                <li><strong>Watch for sheep, cattle and farm vehicles</strong> on country roads, especially in the west.</li>
            </ul>

            <h2>Parking</h2>
            <p>Town parking is usually pay-and-display or by app, and some towns still use a paper parking disc you buy locally. Avoid double-yellow lines and clearways. Most attractions and town centres have dedicated car parks &mdash; an easy option if you're not sure of the local rules.</p>

            <h2>Weather &amp; conditions</h2>
            <p>Rain is frequent and the light changes fast, so keep your dipped headlights on in poor visibility. Roads can be greasy after a dry spell breaks, and exposed coastal and mountain routes get gusty. Snow is rare, but passes can be wet and foggy. Slow down, leave plenty of room, and Irish driving is genuinely enjoyable.</p>
'''

VS_BODY = '''            <p class="lead">It's the happy dilemma of a Kerry road trip: the world-famous Ring of Kerry, or the wilder, quieter Dingle Peninsula just to the north? Both are spectacular, both are on the <a href="/guides/wild-atlantic-way.html">Wild Atlantic Way</a>, and if you possibly can, you should drive both. But if you only have time for one, here's how to choose.</p>

            <h2>How they compare</h2>
            <table class="guide-table">
                <thead><tr><th>&nbsp;</th><th>Ring of Kerry</th><th>Dingle &amp; Slea Head</th></tr></thead>
                <tbody>
                    <tr><td>The drive</td><td>~179 km loop of the Iveragh Peninsula</td><td>~30 km loop of the smaller Dingle Peninsula</td></tr>
                    <tr><td>Time needed</td><td>A full day</td><td>Half to a full day</td></tr>
                    <tr><td>Scenery</td><td>Big and varied: mountains, lakes, coast, islands</td><td>Concentrated, dramatic Atlantic coast and ancient sites</td></tr>
                    <tr><td>Crowds</td><td>Busier; tour coaches drive it too</td><td>Quieter; the narrowest stretches stay coach-free</td></tr>
                    <tr><td>Don't miss</td><td>Skellig views, Sneem, Derrynane, Killarney</td><td>Beehive huts, Dunquin Pier, Gallarus Oratory</td></tr>
                    <tr><td>Best for</td><td>The classic, big-day-out loop</td><td>Wild beauty, heritage and fewer buses</td></tr>
                </tbody>
            </table>

            <h2>The Ring of Kerry</h2>
            <p>The Ring of Kerry is Ireland's most famous scenic drive &mdash; a roughly 179 km loop around the Iveragh Peninsula taking in mountains, the Lakes of Killarney, ancient stone forts, colourful villages like Sneem and Kenmare, and grand views toward the Skellig islands. It's the bigger, more varied day out, and it earns its fame. The trade-off is popularity: tour coaches drive it too (traditionally anti-clockwise), so an early start pays off. Get the full route, the stops and the stories on our <a href="/tours/ring-of-kerry.html">Ring of Kerry audio tour</a>.</p>

            <h2>The Dingle Peninsula &amp; the Slea Head Drive</h2>
            <p>Just to the north, the Dingle Peninsula packs an astonishing amount into a smaller loop. The <a href="/tours/slea-head-drive.html">Slea Head Drive</a> rounds its tip past golden beaches, clifftop beehive huts, the much-photographed Dunquin Pier, the perfectly preserved Gallarus Oratory and views out to the Blasket Islands &mdash; all in a deeply Irish-speaking Gaeltacht. It feels wilder and more intimate than the Ring, and its narrowest sections keep the big coaches out altogether.</p>

''' + MID_CTA + '''

            <h2>Which should you choose?</h2>
            <div class="option-cards two">
                <div class="option-card"><div class="oc-eyebrow">Choose the Ring of Kerry if&hellip;</div><h3>You want the classic</h3><p>It's your first time in Kerry, you want the big, varied, bucket-list loop, and you don't mind sharing the road.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Choose Dingle if&hellip;</div><h3>You want wild &amp; quiet</h3><p>You prefer dramatic coast, ancient sites and a Gaeltacht feel, on a shorter, more concentrated drive with fewer coaches.</p></div>
            </div>

            <h2>Can you do both?</h2>
            <p>Yes &mdash; and it's the answer we'd give if you have two days. The peninsulas sit side by side, so you can drive the Ring of Kerry one day and the Slea Head Drive the next, basing yourself around Killarney or Dingle. With a third day, add the quiet <a href="/tours/skellig-ring.html">Skellig Ring</a> off the western end of the Ring of Kerry for the area's most dramatic, coach-free coast. Our <a href="/guides/wild-atlantic-way.html">Wild Atlantic Way guide</a> shows how all three fit into a longer road trip.</p>
'''

ITIN_BODY = '''            <p class="lead">One week is enough to see the very best of Ireland on a classic self-drive loop from Dublin &mdash; the historic east, the medieval south, the wild peninsulas of Kerry, the great Cliffs of Moher and the buzz of Galway, before crossing the midlands back to the capital. Here's a day-by-day plan that balances driving with time to actually stop and look.</p>

            <h2>The trip at a glance</h2>
            <div class="glance">
                <div class="glance-item"><div class="glance-num">7 days</div><div class="glance-label">A classic first-timer's loop</div></div>
                <div class="glance-item"><div class="glance-num">~900 km</div><div class="glance-label">Total driving, Dublin round-trip</div></div>
                <div class="glance-item"><div class="glance-num">Dublin</div><div class="glance-label">Start and finish &mdash; handy for flights</div></div>
                <div class="glance-item"><div class="glance-num">4 bases</div><div class="glance-label">Dublin, Cork, Killarney &amp; Galway</div></div>
            </div>
            <p>A quick word before you set off: you'll want a hire car, you'll be <a href="/guides/driving-in-ireland.html">driving on the left</a>, and you should book your beds ahead in summer. Download your MacÉireann tours before you go, too &mdash; they run offline on GPS, exactly where the coast loses signal.</p>

            <h2>Day 1 &mdash; Dublin</h2>
            <p class="guide-day"><span class="day-label">Day 1</span>Explore the capital</p>
            <p>Ease in with a day in Dublin: Trinity College and the Book of Kells, Dublin Castle, the Guinness Storehouse and a wander through Temple Bar. No car needed today &mdash; the city is best on foot &mdash; so pick yours up tomorrow morning.</p>

            <p class="guide-day"><span class="day-label">Day 2</span>Dublin to Cork, via the Rock of Cashel</p>
            <p>Head south on the M8 and break the drive at the <strong>Rock of Cashel</strong>, a dramatic clifftop cluster of medieval cathedral, round tower and chapel rising straight out of the Tipperary plain. Carry on to Cork city, or the pretty harbour town of Kinsale, for the night.</p>

            <p class="guide-day"><span class="day-label">Day 3</span>Cork to Killarney</p>
            <p>Drive west into County Kerry &mdash; with an optional stop to kiss the Blarney Stone &mdash; and settle in Killarney, the gateway to the peninsulas, for two nights. Spend the afternoon in Killarney National Park among lakes, woods and Muckross House.</p>

            <p class="guide-day"><span class="day-label">Day 4</span>The Ring of Kerry</p>
            <p>Give the day to the <a href="/tours/ring-of-kerry.html">Ring of Kerry</a>, Ireland's most famous loop &mdash; mountains, ancient forts, colourful villages and island views. Set off early to stay ahead of the tour coaches.</p>

            <p class="guide-day"><span class="day-label">Day 5</span>The Dingle Peninsula</p>
            <p>North to the Dingle Peninsula for the <a href="/tours/slea-head-drive.html">Slea Head Drive</a> &mdash; beehive huts, golden strands, the Gallarus Oratory and the Blasket Islands &mdash; before an evening of music in Dingle town. (Torn between the two peninsulas? Our <a href="/guides/ring-of-kerry-vs-dingle.html">Ring of Kerry vs Dingle</a> guide helps you choose.)</p>

            <p class="guide-day"><span class="day-label">Day 6</span>Kerry to Galway, via the Cliffs of Moher</p>
            <p>Take the Tarbert&ndash;Killimer car ferry across the Shannon into County Clare, then drive the coast with the <a href="/tours/galway-to-cliffs-of-moher.html">Cliffs of Moher and the Burren</a> the highlight of the day &mdash; the <a href="/places/cliffs-of-moher.html">Cliffs of Moher</a> and the lunar <a href="/places/the-burren.html">Burren</a> &mdash; finishing in Galway city.</p>

            <p class="guide-day"><span class="day-label">Day 7</span>Galway to Dublin</p>
            <p>Cross the country back to Dublin with the <a href="/tours/dublin-to-galway.html">Dublin to Galway</a> tour in reverse, the midlands telling their story of Vikings, castles and the mighty Shannon. Drop the car and fly home, full of it.</p>

''' + MID_CTA + '''

            <h2>Tweak the trip to your time</h2>
            <div class="option-cards">
                <div class="option-card"><div class="oc-eyebrow">Only 5 days</div><h3>Skip the south</h3><p>Run Dublin &rarr; Galway &rarr; the Cliffs of Moher &rarr; Kerry and back, dropping the Cork leg to focus on the west coast.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Got 10 days</div><h3>Slow it down</h3><p>Add Connemara west of Galway and a second night on the Dingle Peninsula, and linger longer at every stop.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Two weeks</div><h3>Go the whole way</h3><p>Add the northwest &mdash; Donegal, Sligo and the full <a href="/guides/wild-atlantic-way.html">Wild Atlantic Way</a> &mdash; for the complete coast.</p></div>
            </div>

            <h2>Make the most of the driving days</h2>
            <p>The west-coast portion of this loop &mdash; Kerry, Clare and Galway &mdash; is the heart of the <a href="/guides/wild-atlantic-way.html">Wild Atlantic Way</a>, so see that guide for the coastal stretch in depth. And whenever you go, the weather and daylight shape what's possible: our guide to <a href="/guides/best-time-to-visit-ireland.html">the best time to visit Ireland</a> will help you pick your week.</p>
'''

BESTTIME_BODY = '''            <p class="lead">Ireland is a year-round destination, but the best time for a road trip depends on what you're after: long days and lively towns, or quiet roads and lower prices. The short answer most locals would give you is late spring and early autumn &mdash; <strong>May and September</strong> &mdash; when you get much of the summer's good weather without the summer's crowds.</p>

            <h2>The season in numbers</h2>
            <div class="glance">
                <div class="glance-item"><div class="glance-num">May&ndash;Sep</div><div class="glance-label">Best weather and longest days</div></div>
                <div class="glance-item"><div class="glance-num">June</div><div class="glance-label">Daylight lasts until nearly 11pm</div></div>
                <div class="glance-item"><div class="glance-num">May &amp; Sep</div><div class="glance-label">The quiet sweet spot</div></div>
                <div class="glance-item"><div class="glance-num">Jul&ndash;Aug</div><div class="glance-label">Peak season &mdash; busiest and priciest</div></div>
            </div>

            <h2>Season by season</h2>
            <div class="option-cards">
                <div class="option-card"><div class="oc-eyebrow">Spring · Mar&ndash;May</div><h3>Fresh &amp; green</h3><p>Lengthening days and fewer crowds. April can be showery but bright, and by May the Burren's wildflowers are out and the coast roads are a joy.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Summer · Jun&ndash;Aug</div><h3>Long &amp; lively</h3><p>The warmest weather, the longest days and everything open. Also the busiest and dearest, so book accommodation well ahead.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Autumn · Sep&ndash;Nov</div><h3>Quiet &amp; golden</h3><p>September is often glorious and far calmer than midsummer; October brings colour. By November it turns wet and dark.</p></div>
                <div class="option-card"><div class="oc-eyebrow">Winter · Dec&ndash;Feb</div><h3>Wild &amp; cosy</h3><p>Short days and some seasonal closures, but empty roads, dramatic coasts, turf fires and cities glowing at Christmas.</p></div>
            </div>

            <h2>Month by month at a glance</h2>
            <table class="guide-table">
                <thead><tr><th>Month</th><th>Daylight</th><th>What to expect</th></tr></thead>
                <tbody>
                    <tr><td>January</td><td>~8 hrs</td><td>Coldest and quietest; wild coasts, cosy pubs, some closures.</td></tr>
                    <tr><td>February</td><td>~9.5 hrs</td><td>Still wintry but brightening; great value.</td></tr>
                    <tr><td>March</td><td>~11.5 hrs</td><td>Spring stirs; St Patrick's Day livens up the towns.</td></tr>
                    <tr><td>April</td><td>~13.5 hrs</td><td>Showery but bright, lambs in the fields, fewer visitors.</td></tr>
                    <tr><td>May</td><td>~15.5 hrs</td><td>A sweet spot: long days, wildflowers, quiet roads.</td></tr>
                    <tr><td>June</td><td>~17 hrs</td><td>Peak daylight to nearly 11pm; warm and lively, filling up.</td></tr>
                    <tr><td>July&ndash;August</td><td>~16 hrs</td><td>Warmest and busiest; book everything ahead.</td></tr>
                    <tr><td>September</td><td>~12.5 hrs</td><td>The other sweet spot: mild, calmer, still green.</td></tr>
                    <tr><td>October</td><td>~10.5 hrs</td><td>Autumn colour and atmosphere; cooler and wetter.</td></tr>
                    <tr><td>Nov&ndash;December</td><td>~8 hrs</td><td>Short, dark days; festive cities; lowest prices.</td></tr>
                </tbody>
            </table>

''' + MID_CTA + '''

            <h2>What the weather is actually like</h2>
            <p>Ireland's weather is mild rather than extreme, and famously changeable &mdash; locals talk about "four seasons in a day," and they're not joking. Summer temperatures usually sit around 15&ndash;20&deg;C, winters rarely drop far below freezing, and rain is possible in any month, blowing through in showers as often as settling in for the day. Snow is uncommon outside the hills. The practical upshot: pack layers and a good waterproof whatever the season, and don't let a grey morning put you off &mdash; it often burns through by afternoon.</p>

            <h2>Crowds, prices and booking ahead</h2>
            <p>July and August are the peak, when families travel and the honeypots &mdash; the Cliffs of Moher, the Ring of Kerry, Killarney &mdash; are at their busiest and accommodation at its priciest. The shoulder months of May, June and September give you the best balance of weather, daylight and elbow room. Winter is cheapest and quietest, but plan around shorter days and the odd seasonal closure. Whenever you travel, an early start puts you at the famous spots before the coaches arrive.</p>

            <h2>The best time for&hellip;</h2>
            <ul style="font-size:1.08rem; color:#3a463f; margin:0 0 18px 22px; line-height:1.7;">
                <li><strong>Best weather &amp; long driving days:</strong> June and July, with daylight stretching past 10pm.</li>
                <li><strong>The sweet spot (weather vs crowds):</strong> May and September.</li>
                <li><strong>Wildflowers in the <a href="/places/the-burren.html">Burren</a>:</strong> May into June, when Arctic and Mediterranean plants bloom together.</li>
                <li><strong>Fewest crowds &amp; lowest prices:</strong> November to February, outside the Christmas period.</li>
                <li><strong>Atmosphere &amp; empty roads:</strong> winter &mdash; just keep drives short, as the light fades by mid-afternoon (see our <a href="/guides/driving-in-ireland.html">driving in Ireland</a> guide).</li>
            </ul>
'''

GUIDES = [
 {
  'slug': 'wild-atlantic-way', 'crumb': 'Wild Atlantic Way',
  'region': 'Trip-Planning Guide',
  'h1': 'How to Drive the Wild Atlantic Way: The Complete Guide',
  'title': 'How to Drive the Wild Atlantic Way: Route, Itinerary & Tips | MacÉireann',
  'meta': "How to drive the Wild Atlantic Way: how many days you need, where to start, the route region by region, a 7-day itinerary and practical tips for Ireland's epic coastal road trip.",
  'ogtitle': 'How to Drive the Wild Atlantic Way: The Complete Guide',
  'ogdesc': "How many days you need, where to start, the route region by region, and a ready-made 7-day itinerary for Ireland's 2,500 km coastal road trip.",
  'img': '/newimages/road-signs.webp',
  'tagline': "Everything you need to plan Ireland's greatest road trip — how long it takes, where to start, and a day-by-day itinerary for the best of the coast.",
  'published': '2026-06-18', 'modified': '2026-06-18',
  'body': WAW_BODY,
  'cta_h2': 'Drive the Wild Atlantic Way with its stories',
  'cta_p': "MacÉireann turns the west-coast drive into a guided tour — legends, history and local lore narrated turn-by-turn as you go, and working offline where the coast has no signal. Pick your routes and let a traditional storyteller ride shotgun.",
  'related': [
    ('/tours/ring-of-kerry.html', 'Ring of Kerry', '/newimages/ringofkerry.webp'),
    ('/places/cliffs-of-moher.html', 'Cliffs of Moher', '/newimages/cliffs-of-moher.webp'),
    ('/tours/slea-head-drive.html', 'Slea Head Drive', '/newimages/slea-head.webp'),
  ],
  'faqs': [
    ('How long does it take to drive the Wild Atlantic Way?', "Driving the full 2,500 km route from Donegal to Cork takes around 10 to 14 days with stops. If you only have a week, focus on the southwest — Galway, the Burren, the Cliffs of Moher and the Kerry peninsulas — which holds many of the highlights."),
    ('Which direction should you drive the Wild Atlantic Way?', "Most people drive it north to south, from Donegal down to Kinsale in Cork, but either direction works and most visitors drive just one section. Many start from Dublin and head west to Galway to join the route."),
    ('What is the best part of the Wild Atlantic Way?', "For most first-time visitors the southwest is the highlight: the Cliffs of Moher and the Burren in County Clare, and the three Kerry peninsulas — the Ring of Kerry, the Slea Head Drive on the Dingle Peninsula, and the Skellig Ring."),
    ('Do you need a car to drive the Wild Atlantic Way?', "Yes — it's a self-drive touring route, and a car gives you the freedom to stop wherever you like. The coastal roads are narrow and winding, so take them slowly, and remember Ireland drives on the left."),
    ('When is the best time of year to drive the Wild Atlantic Way?', "May to September for the best weather and longest days, with May and September quieter than the July–August peak. The route is open year-round, but winter brings short days and some seasonal closures."),
    ('Do the MacÉireann audio tours work without phone signal?', "Yes. Download each tour before you set off and it uses your phone's GPS to play the stories automatically, so it keeps working on the remote coastal stretches where there's no mobile coverage."),
  ],
 },
 {
  'slug': 'driving-in-ireland', 'crumb': 'Driving in Ireland',
  'region': 'Trip-Planning Guide',
  'h1': 'Driving in Ireland: Tips for First-Timers',
  'title': 'Driving in Ireland: Tips for First-Timers (2026 Guide) | MacÉireann',
  'meta': "Driving in Ireland for the first time? Which side of the road, hiring a car, speed limits, tolls, narrow roads and the rules of the road — everything a visitor needs to drive with confidence.",
  'ogtitle': 'Driving in Ireland: Tips for First-Timers',
  'ogdesc': "Which side of the road, hiring a car, speed limits, tolls and narrow roads — everything a visitor needs to drive Ireland with confidence.",
  'img': '/newimages/discover.webp',
  'tagline': "Which side of the road, hiring a car, the rules and the narrow lanes — everything a visitor needs to drive Ireland with confidence.",
  'published': '2026-06-18', 'modified': '2026-06-18',
  'body': DRIVING_BODY,
  'cta_h2': 'Turn the drive into the highlight',
  'cta_p': "Once you're on the road, let MacÉireann do the talking — legends, history and local lore narrated automatically as you reach each place, and working offline where the coast has no signal.",
  'related': [
    ('/guides/wild-atlantic-way.html', 'Wild Atlantic Way Guide', '/newimages/road-signs.webp'),
    ('/tours/ring-of-kerry.html', 'Ring of Kerry', '/newimages/ringofkerry.webp'),
    ('/tours/', 'All audio tours', '/newimages/slea-head.webp'),
  ],
  'faqs': [
    ('Which side of the road do you drive on in Ireland?', "Ireland drives on the left, with the driver seated on the right of the car. A useful reminder is that the driver should always be nearest the centre line of the road."),
    ('Is it hard to drive in Ireland?', "Not really. The two adjustments for most visitors are driving on the left and the narrow, winding rural roads. Take an easy first drive, go slowly on country lanes, and it becomes comfortable within a day."),
    ('Can I drive in Ireland with my own licence?', "Visitors can generally drive on a valid full licence from their home country for the length of a normal visit. Carry the physical licence with you, and check whether your country's licence needs an International Driving Permit alongside it."),
    ('Should I rent a manual or an automatic car?', "Most hire cars in Ireland are manual. If you can't drive a manual, book an automatic well in advance, as they are fewer and tend to cost more."),
    ('Do you have to pay tolls when driving in Ireland?', "A few motorways have tolls paid at barriers by cash or card. Dublin's M50 is barrier-free and must be paid online by 8pm the next day — check how your hire company handles it."),
    ('Do the MacÉireann audio tours need phone signal?', "No. Download a tour before you set off and it plays each story automatically using your phone's GPS, so it works even where there's no mobile coverage."),
  ],
 },
 {
  'slug': 'ring-of-kerry-vs-dingle', 'crumb': 'Ring of Kerry vs Dingle',
  'region': 'Trip-Planning Guide',
  'h1': 'Ring of Kerry vs the Dingle Peninsula: Which Should You Drive?',
  'title': 'Ring of Kerry vs Dingle: Which Should You Drive? | MacÉireann',
  'meta': "Ring of Kerry or the Dingle Peninsula? A side-by-side comparison of Kerry's two great drives — length, scenery, crowds and highlights — to help you choose (or do both).",
  'ogtitle': 'Ring of Kerry vs Dingle: Which Should You Drive?',
  'ogdesc': "A side-by-side comparison of Kerry's two great coastal drives — length, scenery, crowds and highlights — to help you choose, or do both.",
  'img': '/newimages/ringofkerry.webp',
  'tagline': "Kerry's two great drives, compared side by side — so you can pick the right one, or make room for both.",
  'published': '2026-06-18', 'modified': '2026-06-18',
  'body': VS_BODY,
  'cta_h2': 'Drive Kerry with a storyteller aboard',
  'cta_p': "Whichever you choose, MacÉireann narrates the legends, history and local lore turn-by-turn as you drive — and works offline where the coast has no signal. Download the Ring of Kerry and Slea Head tours and let a storyteller ride shotgun.",
  'related': [
    ('/tours/ring-of-kerry.html', 'Ring of Kerry', '/newimages/ringofkerry.webp'),
    ('/tours/slea-head-drive.html', 'Slea Head Drive', '/newimages/slea-head.webp'),
    ('/tours/skellig-ring.html', 'Skellig Ring', '/newimages/road-signs.webp'),
  ],
  'faqs': [
    ('Is the Ring of Kerry or Dingle better?', "Both are spectacular. The Ring of Kerry is the bigger, more varied loop and the more famous; the Dingle Peninsula is wilder, quieter and more concentrated. If you can, drive both — they sit side by side."),
    ('Can you drive both the Ring of Kerry and Dingle in one day?', "Not comfortably. Each deserves the best part of a day, so two days is ideal — the Ring of Kerry one day and the Slea Head Drive on Dingle the next."),
    ('Which is less crowded, the Ring of Kerry or Dingle?', "The Dingle Peninsula and its Slea Head Drive are generally quieter, and the narrowest coastal stretches are too tight for tour coaches, so they stay peaceful."),
    ('How long does the Ring of Kerry take compared to Dingle?', "The Ring of Kerry is a ~179 km loop that fills a full day. The Slea Head Drive on Dingle is a much shorter loop of around 30 km, taking half a day to a full day with stops."),
    ('Do I need a guide to drive them?', "No — both are self-drive routes. The MacÉireann app narrates each one turn-by-turn using your phone's GPS, and works offline where there's no signal."),
  ],
 },
 {
  'slug': '7-day-ireland-itinerary', 'crumb': '7-Day Ireland Itinerary',
  'region': 'Trip-Planning Guide',
  'h1': 'The Perfect 7-Day Ireland Road Trip Itinerary',
  'title': 'The Perfect 7-Day Ireland Road Trip Itinerary | MacÉireann',
  'meta': "A perfect 7-day Ireland road trip itinerary: a day-by-day self-drive loop from Dublin through the Rock of Cashel, Kerry, the Cliffs of Moher and Galway — with drive times and audio tours.",
  'ogtitle': 'The Perfect 7-Day Ireland Road Trip Itinerary',
  'ogdesc': "A day-by-day self-drive loop from Dublin through the south, Kerry, the Cliffs of Moher and Galway — one perfect week in Ireland.",
  'img': '/newimages/slea-head.webp',
  'tagline': "One perfect week, one classic loop — a day-by-day self-drive plan from Dublin through Kerry, Clare and Galway and back.",
  'published': '2026-06-18', 'modified': '2026-06-18',
  'body': ITIN_BODY,
  'cta_h2': 'Make every driving day a guided tour',
  'cta_p': "MacÉireann narrates the legends and history of each leg as you drive it — from the midlands crossing to the Ring of Kerry and the Cliffs of Moher — automatically and offline. Download the routes and let a storyteller ride shotgun all week.",
  'related': [
    ('/tours/ring-of-kerry.html', 'Ring of Kerry', '/newimages/ringofkerry.webp'),
    ('/tours/slea-head-drive.html', 'Slea Head Drive', '/newimages/slea-head.webp'),
    ('/guides/wild-atlantic-way.html', 'Wild Atlantic Way Guide', '/newimages/road-signs.webp'),
  ],
  'faqs': [
    ('Is 7 days enough to see Ireland?', "Yes, for the highlights. A week is enough to loop from Dublin through the medieval south, the Kerry peninsulas, the Cliffs of Moher and Galway. You won't see everything, but you'll see the best of it without rushing every day."),
    ('Can you drive around Ireland in a week?', "You can comfortably drive a southern loop of Ireland in a week — Dublin to Cork, Kerry, Clare and Galway and back. Driving the entire coast, including the north, needs closer to two weeks."),
    ('What is the best 7-day road trip route in Ireland?', "The classic loop runs Dublin → Cork (via the Rock of Cashel) → Killarney and the Ring of Kerry → the Dingle Peninsula → the Cliffs of Moher and the Burren → Galway → back to Dublin."),
    ('Do you need a car for an Ireland road trip?', "Yes. A car gives you the freedom to follow the coast roads and stop where you like; public transport is limited on the scenic rural routes. Remember that Ireland drives on the left."),
    ('How much driving is a week in Ireland?', "This loop is around 900 km (roughly 560 miles) in total, spread across the week, with the longest single days being the Dublin–Cork and Galway–Dublin legs."),
    ('Do the MacÉireann tours work offline?', "Yes. Download each tour before you set off and it plays automatically using your phone's GPS, so it works even on the remote stretches with no mobile coverage."),
  ],
 },
 {
  'slug': 'best-time-to-visit-ireland', 'crumb': 'Best Time to Visit',
  'region': 'Trip-Planning Guide',
  'h1': 'The Best Time to Visit Ireland for a Road Trip',
  'title': 'The Best Time to Visit Ireland for a Road Trip | MacÉireann',
  'meta': "When is the best time to visit Ireland? A season-by-season and month-by-month guide to weather, daylight, crowds and prices — and why May and September are the sweet spot.",
  'ogtitle': 'The Best Time to Visit Ireland for a Road Trip',
  'ogdesc': "A season-by-season and month-by-month guide to Ireland's weather, daylight, crowds and prices — and why May and September are the sweet spot.",
  'img': '/newimages/doolin.webp',
  'tagline': "Weather, daylight, crowds and prices through the year — and why late spring and early autumn are the sweet spot for a road trip.",
  'published': '2026-06-18', 'modified': '2026-06-18',
  'body': BESTTIME_BODY,
  'cta_h2': 'Whenever you go, drive it with its stories',
  'cta_p': "MacÉireann narrates the legends, history and local lore of the road as you drive — turn-by-turn, automatically, and offline where the coast has no signal. Pick your routes and let a traditional storyteller ride shotgun.",
  'related': [
    ('/guides/wild-atlantic-way.html', 'Wild Atlantic Way Guide', '/newimages/road-signs.webp'),
    ('/places/the-burren.html', 'The Burren', '/newimages/burren.webp'),
    ('/tours/ring-of-kerry.html', 'Ring of Kerry', '/newimages/ringofkerry.webp'),
  ],
  'faqs': [
    ('What is the best month to visit Ireland?', "May, June and September are the best months — long days and generally good weather, with May and September quieter and cheaper than the July–August peak."),
    ('Is Ireland worth visiting in winter?', "Yes, if you want atmosphere, low prices and empty roads. The trade-offs are short days (light fades by mid-afternoon) and some seasonal closures, especially on the remote coast."),
    ('What is the wettest time of year in Ireland?', "Autumn and winter, roughly October to January, are the wettest and windiest, though rain is possible in any month — it usually blows through in showers rather than settling in all day."),
    ('When is Ireland least crowded?', "Outside July and August and the main holidays. The shoulder months of May and September give you quiet roads with good weather, while winter is the quietest and cheapest of all."),
    ('What is the weather like in Ireland in summer?', "Mild rather than hot — typically 15 to 20°C, changeable, with very long daylight and a mix of sunshine and passing showers. Pack layers and a waterproof whatever the forecast."),
  ],
 },
]

for g in GUIDES:
    build(g)
