# -*- coding: utf-8 -*-
"""MacEireann attraction / hotspot page generator.
Run from the repo root:  python3 tools/gen_places.py
Edit the PLACES data below (not the generated .html) and re-run so every
attraction page stays consistent. Styling lives in tours/tour.css.
Sibling of tools/gen_tours2.py — same look, different page type.
"""
import html
import json

APP_URL = "https://apps.apple.com/app/id6774573617"

APP_BADGE = ('<a class="app-store-btn" href="' + APP_URL + '" aria-label="Download MacEireann on the App Store">'
 '<svg viewBox="0 0 384 512" width="24" height="24" fill="currentColor" aria-hidden="true">'
 '<path d="M318.7 268.7c-.2-36.7 16.4-64.4 50-84.8-18.8-26.9-47.2-41.7-84.7-44.6-35.5-2.8-74.3 20.7-88.5 20.7-15 0-49.4-19.7-76.4-19.7C63.3 141.2 4 184.8 4 273.5q0 39.3 14.4 81.2c12.8 36.7 59 126.7 107.2 125.2 25.2-.6 43-17.9 75.8-17.9 31.8 0 48.3 17.9 76.4 17.9 48.6-.7 90.4-82.5 102.6-119.3-65.2-30.7-61.7-90-61.7-91.9zm-56.6-164.2c27.3-32.4 24.8-61.9 24-72.5-24.1 1.4-52 16.4-67.9 34.9-17.5 19.8-27.8 44.3-25.6 71.9 26.1 2 49.9-11.4 69.5-34.3z"/>'
 '</svg><span class="ass-text"><small>Download on the</small><strong>App Store</strong></span></a>')

ICONS = {
  'pin':'<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"></path><circle cx="12" cy="10" r="3"></circle>',
  'park':'<rect x="3" y="3" width="18" height="18" rx="3"></rect><path d="M9 17V7h3.5a3 3 0 0 1 0 6H9"></path>',
  'clock':'<circle cx="12" cy="12" r="10"></circle><polyline points="12 6 12 12 16 14"></polyline>',
  'cost':'<rect x="1" y="4" width="22" height="16" rx="2"></rect><line x1="1" y1="10" x2="23" y2="10"></line>',
  'cal':'<rect x="3" y="4" width="18" height="18" rx="2"></rect><line x1="16" y1="2" x2="16" y2="6"></line><line x1="8" y1="2" x2="8" y2="6"></line><line x1="3" y1="10" x2="21" y2="10"></line>',
  'access':'<circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="11"></line><line x1="12" y1="8" x2="12.01" y2="8"></line>',
}
INFO_ORDER = [('pin','Getting there'),('park','Parking'),('clock','Time needed'),
              ('cost','Cost'),('cal','Best time to visit'),('access','Accessibility')]

def ico(kind):
    return (f'<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" '
            f'stroke-width="2" stroke-linecap="round" stroke-linejoin="round">{ICONS[kind]}</svg>')

TPL = '''<!DOCTYPE html>
<!--
  MacEireann PLACE / ATTRACTION PAGE  (generated by tools/gen_places.py)
  To change copy permanently, edit the generator, not this file, so all
  attraction pages stay consistent. Styling lives in /tours/tour.css.
-->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <title>{title}</title>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora:ital,wght@0,400..700;1,400..700&family=Inter:wght@300;400;500;600;700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Uncial+Antiqua&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/tours/tour.css">

    <link rel="canonical" href="https://maceireann.ie/places/{slug}.html">
    <meta name="description" content="{meta}">
    <meta name="robots" content="index, follow, max-image-preview:large">
    <meta name="theme-color" content="#0F291E">

    <meta property="og:title" content="{ogtitle}">
    <meta property="og:description" content="{ogdesc}">
    <meta property="og:type" content="article">
    <meta property="og:url" content="https://maceireann.ie/places/{slug}.html">
    <meta property="og:image" content="https://maceireann.ie{ogimg}">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:site_name" content="MacÉireann">
    <meta property="og:locale" content="en_IE">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:image" content="https://maceireann.ie{ogimg}">

    <link rel="icon" href="/images/logo.png" sizes="32x32" type="image/png">
    <link rel="apple-touch-icon" href="/images/logo.png">

    <script type="application/ld+json">
    {{
      "@context": "https://schema.org",
      "@type": "TouristAttraction",
      "name": "{name}",
      "description": "{meta}",
      "url": "https://maceireann.ie/places/{slug}.html",
      "image": "https://maceireann.ie{ogimg}",
      "geo": {{ "@type": "GeoCoordinates", "latitude": {lat}, "longitude": {lon} }},
      "address": {{ "@type": "PostalAddress", "addressRegion": "{county}", "addressCountry": "IE" }},
      "isAccessibleForFree": {free},
      "touristType": {tourist_type}
    }}
    </script>
    <script type="application/ld+json">
    {{
      "@context": "https://schema.org",
      "@type": "BreadcrumbList",
      "itemListElement": [
        {{ "@type": "ListItem", "position": 1, "name": "Home", "item": "https://maceireann.ie/" }},
        {{ "@type": "ListItem", "position": 2, "name": "Places", "item": "https://maceireann.ie/places/" }},
        {{ "@type": "ListItem", "position": 3, "name": "{h1}", "item": "https://maceireann.ie/places/{slug}.html" }}
      ]
    }}
    </script>
{faq_schema}    <script defer src="/analytics.js"></script>
</head>
<body>

    <nav class="tour-nav">
        <a class="brand" href="/">
            <img src="/images/logo.png" alt="MacÉireann logo">
            <span class="brand-name">MacÉireann</span>
        </a>
        {app_badge}
    </nav>

    <header class="tour-hero" style="background-image: url('{img}');">
        <div class="container hero-inner">
            <span class="tour-region">{region}</span>
            <h1>{h1} — A Visitor's Guide</h1>
            <p class="tagline">{tagline}</p>
        </div>
    </header>

    <main class="tour-body">
        <div class="container">
            <p class="breadcrumb"><a href="/">Home</a> &rsaquo; <a href="/places/">Places</a> &rsaquo; {h1}</p>

            <p class="lead">{lead}</p>
            <p>{intro}</p>

            <a class="audio-sample" href="{app_url}">
                <span class="play-btn">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="currentColor"><polygon points="6 4 20 12 6 20 6 4"></polygon></svg>
                </span>
                <div>
                    <h4>Hear the full story in the app</h4>
                    <p>Narrated by a traditional storyteller and triggered automatically as you drive past. Download on the App Store &rarr;</p>
                </div>
            </a>

            <h2>Plan your visit</h2>
            <div class="visit-info">{info_html}</div>

            <h2>The story</h2>
            {story_html}
            <div class="story-snippet">
                <p class="eyebrow">In the app</p>
                <p>{snippet}</p>
            </div>
            <p>That is just a taste. Hear the full story — and the legends, history and local lore of every place along the way — narrated automatically in the MacÉireann app as you drive past.</p>

            <h2>Drive it as part of a tour</h2>
            <p>{tours_intro}</p>
            <div class="related-grid">{route_html}</div>

{faq_block}            <div class="tour-cta" id="get-the-app">
                <h2>Hear {h1} come to life</h2>
                <p>MacÉireann is live on the App Store. Pick the route that passes {h1}, download it before you set off, and let a traditional storyteller narrate it as you drive.</p>
                {app_badge}
                <div class="cta-secondary">
                    <p>Not travelling yet? Get trip-planning tips and new-tour news by email.</p>
                    <form class="waitlist-form" data-source="place-{slug}">
                        <input type="email" placeholder="Enter your email" required>
                        <button type="submit">Keep Me Posted</button>
                    </form>
                    <p class="signup-msg hidden"></p>
                </div>
            </div>
        </div>
    </main>

    <section class="related">
        <div class="container">
            <h2>More to explore</h2>
            <div class="related-grid">{related_html}</div>
        </div>
    </section>

    <footer>
        <div class="links">
            <a href="/">Home</a>
            <a href="/tours/">All Tours</a>
            <a href="/places/">Places</a>
            <a href="/guides/">Guides</a>
            <a href="/about.html">About</a>
            <a href="/privacy.html">Privacy</a>
            <a href="/support.html">Support</a>
            <a href="#" data-cookie-settings>Cookie settings</a>
        </div>
        <p>© 2026 Yarn Point Tours Ltd. All Rights Reserved.</p>
        <p class="slainte">Sláinte!</p>
    </footer>

    <script src="/tours/tour-signup.js"></script>
</body>
</html>
'''

def build(p):
    ogimg = '/newimages/og/' + p['slug'] + '-og.jpg'
    info_html = ''.join(
        f'\n                <div class="vi-item"><span class="vi-ico">{ico(k)}</span>'
        f'<div class="vi-text"><div class="vi-label">{label}</div>'
        f'<div class="vi-value">{p["info"][k]}</div></div></div>'
        for k, label in INFO_ORDER) + '\n            '
    story_html = ''.join('<p>' + para + '</p>\n            ' for para in p['story']).rstrip()
    route_html = ''.join(
        f'\n                <a class="related-card" href="/tours/{r[0]}.html" style="background-image:url(\'{r[2]}\');"><span>{r[1]}</span></a>'
        for r in p['routes']) + '\n            '
    related_html = ''.join(
        f'\n                <a class="related-card" href="{r[0]}" style="background-image:url(\'{r[2]}\');"><span>{r[1]}</span></a>'
        for r in p['related']) + '\n            '
    faqs = p.get('faqs', [])
    if faqs:
        faq_items = ''.join(
            '\n                <div class="faq-item"><h3>' + html.escape(q) + '</h3><p>' + html.escape(a) + '</p></div>'
            for q, a in faqs) + '\n            '
        faq_block = ('            <h2>Common questions</h2>\n            <div class="faq">'
                     + faq_items + '</div>\n\n')
        faq_data = {"@context": "https://schema.org", "@type": "FAQPage",
                    "mainEntity": [{"@type": "Question", "name": q,
                                    "acceptedAnswer": {"@type": "Answer", "text": a}} for q, a in faqs]}
        faq_schema = '    <script type="application/ld+json">\n    ' + json.dumps(faq_data, ensure_ascii=False) + '\n    </script>\n'
    else:
        faq_block = ''
        faq_schema = ''
    data = {k: v for k, v in p.items()
            if k not in ('info', 'story', 'routes', 'related', 'faqs', 'tourist_type')}
    out = TPL.format(
        app_url=APP_URL, app_badge=APP_BADGE, ogimg=ogimg,
        info_html=info_html, story_html=story_html, route_html=route_html,
        related_html=related_html, faq_block=faq_block, faq_schema=faq_schema,
        tourist_type=json.dumps(p['tourist_type']), **data)
    with open(f"places/{p['slug']}.html", 'w') as f:
        f.write(out)
    print(f"wrote places/{p['slug']}.html ({len(faqs)} FAQs)")


PLACES = [
 {
  'slug': 'cliffs-of-moher', 'name': 'Cliffs of Moher', 'h1': 'Cliffs of Moher',
  'region': 'County Clare · Wild Atlantic Way',
  'county': 'County Clare', 'lat': 52.9719, 'lon': -9.4262, 'free': 'false',
  'tourist_type': ['Sightseeing', 'Nature', 'Heritage'],
  'title': 'Cliffs of Moher: Visitor Guide, Tickets, Parking & Best Time | MacÉireann',
  'meta': "A complete guide to visiting the Cliffs of Moher in County Clare — how to get there, parking, tickets, the best time to go, and the legends behind Ireland's most famous cliffs.",
  'ogtitle': 'Cliffs of Moher — A Visitor\'s Guide',
  'ogdesc': "Everything you need to visit Ireland's most famous cliffs: how to get there, when to go, and the folklore behind the 214-metre drop.",
  'img': '/newimages/cliffs-of-moher.webp',
  'tagline': "214 metres of sheer Atlantic cliff on the edge of County Clare — Ireland's most visited natural wonder, and a wall of folklore as well as rock.",
  'lead': "The Cliffs of Moher rise straight from the Atlantic for as much as 214 metres and run for around 14 kilometres along the Clare coast, from Hag's Head in the south to beyond O'Brien's Tower in the north. On a clear day you can see the Aran Islands, the hills of Connemara and the whole sweep of Galway Bay. It is the most visited natural attraction in Ireland — and with good reason.",
  'intro': "This guide covers the practical side of a visit — getting there, parking, tickets, timing and access — and then the part most guidebooks skip: the legends carved into this coast. Plan your visit here for free, then let MacÉireann narrate the cliffs and the whole drive around them as you go.",
  'info': {
    'pin': "On the R478 near Liscannor, County Clare — about 1 hour (70 km) from Galway and 1.5 hours from Limerick, signposted off the Wild Atlantic Way.",
    'park': "Large visitor-centre car park; the parking charge is included in your admission ticket.",
    'clock': "Allow 1.5 to 2 hours for the visitor centre, O'Brien's Tower and the cliff-edge paths.",
    'cost': "Paid admission to the visitor experience — book a timed ticket online in advance for the best rate (it covers parking too).",
    'cal': "Early morning or near sunset to beat the midday coaches; May to September for the kindest weather.",
    'access': "Paved, accessible viewing platforms near the visitor centre; the trails further along the cliff edge are uneven and exposed.",
  },
  'story': [
    "The cliffs are named for a long-vanished promontory fort — <em>Mothar</em> — that once stood at Hag's Head, the headland at their southern end. Hag's Head itself, <em>Ceann na Caillí</em>, \"the head of the hag,\" remembers Mal, a witch who fell for the hero Cú Chulainn and chased him along the coast. He leapt across the sea stacks to escape her; she leapt after him, fell short, and was dashed on the rocks below — and the sea ran red, so they say, as far as Liscannor.",
    "O'Brien's Tower, the little round lookout at the highest point, was built in 1835 by Cornelius O'Brien, a local landlord and member of parliament, to impress visitors — an early piece of tourism that worked rather well. Below it, the sea stack called Branaunmore was once part of the cliff itself before the Atlantic cut it loose.",
    "The ledges are a seabird city in summer — puffins, razorbills, guillemots and kittiwakes nesting in their thousands — and the cliffs have stood in for far-off lands on screen, from the Cliffs of Insanity in <em>The Princess Bride</em> to a sea cave in <em>Harry Potter and the Half-Blood Prince</em>.",
  ],
  'snippet': "\"They called it the Cliff of the Foals — Aill na Searrach — for the seven young horses that sprang from the waves, ran wild across Clare for a day and a night, then leapt from this very edge back into the sea they came from.\"",
  'tours_intro': "The Cliffs of Moher are the highlight of MacÉireann's Clare coast tour, narrated turn-by-turn whichever way you drive it:",
  'routes': [
    ('cliffs-of-moher-to-galway', 'Cliffs of Moher to Galway', '/newimages/cliffs-of-moher.webp'),
    ('galway-to-cliffs-of-moher', 'Galway to Cliffs of Moher', '/newimages/burren.webp'),
  ],
  'related': [
    ('/places/the-burren.html', 'The Burren', '/newimages/burren.webp'),
    ('/tours/ring-of-kerry.html', 'Ring of Kerry', '/newimages/ringofkerry.webp'),
    ('/tours/', 'All audio tours', '/newimages/slea-head.webp'),
  ],
  'faqs': [
    ('How much does it cost to visit the Cliffs of Moher?', "Entry to the Cliffs of Moher Experience is by paid admission, and your ticket includes parking. Booking a timed ticket online in advance is cheaper than paying at the gate, and guarantees your slot in summer."),
    ('How long do you need at the Cliffs of Moher?', "Most visitors spend about 1.5 to 2 hours — enough for the visitor centre, the climb to O'Brien's Tower and a walk along the cliff-edge paths. Keen walkers can follow the longer coastal trail toward Doolin or Liscannor."),
    ('When is the best time to visit the Cliffs of Moher?', "Early morning or near sunset, outside the busy midday window when the tour coaches arrive. For weather, May to September is best, though the cliffs are dramatic in any season."),
    ('Can you visit the Cliffs of Moher for free?', "You can reach the cliffs on foot along the coastal walk from Doolin or Liscannor without entering the paid Experience, but the official car park and visitor centre require a ticket."),
    ('Do I need a phone signal for the audio tour?', "No. Download the tour before you set off and it uses your phone's GPS to play each story automatically, so it works even where there is no mobile coverage."),
  ],
 },
 {
  'slug': 'the-burren', 'name': 'The Burren', 'h1': 'The Burren',
  'region': 'County Clare · Wild Atlantic Way',
  'county': 'County Clare', 'lat': 53.0833, 'lon': -9.0833, 'free': 'true',
  'tourist_type': ['Nature', 'Heritage', 'Sightseeing'],
  'title': 'The Burren, Ireland: Visitor Guide, Things to Do & Best Time | MacÉireann',
  'meta': "A guide to the Burren in County Clare — the unique limestone landscape, its rare wildflowers and ancient tombs, how to explore it, the best time to visit, and the stories beneath the stone.",
  'ogtitle': 'The Burren — A Visitor\'s Guide',
  'ogdesc': "Ireland's lunar limestone landscape, where Arctic and Mediterranean wildflowers bloom from bare grey rock. How to explore it, and the stories beneath the stone.",
  'img': '/newimages/burren.webp',
  'tagline': "A vast pavement of bare grey limestone in north County Clare — a lunar landscape where rare wildflowers bloom from the rock and 6,000 years of history lie open to the sky.",
  'lead': "The Burren — from the Irish <em>Boireann</em>, \"a rocky place\" — is a great expanse of fissured limestone covering some 250 square kilometres of north County Clare and the edge of south Galway. It looks, at first, like a stone desert. Look closer and it is one of the richest botanical sites in Ireland, where Arctic, Alpine and Mediterranean plants grow side by side in the cracks of the rock, and where dolmens and ring forts stand among the most ancient in the country.",
  'intro': "This guide covers how to explore the Burren — getting there, where to go, the best time for the flowers and the access to expect — and the long human story written into its stone. Plan your visit here for free, then let MacÉireann narrate the landscape as you drive through it.",
  'info': {
    'pin': "North County Clare, between Ballyvaughan, Kilfenora and Corofin, on and off the N67 coast road — about 40 minutes from Galway city.",
    'park': "Car parks at the main sites — Poulnabrone dolmen, the Burren National Park and Aillwee Cave — most of them free.",
    'clock': "Half a day to a full day, depending on how many sites and walks you take in.",
    'cost': "Free to roam, and the Burren National Park is free to enter; paid attractions include Aillwee Cave and Caherconnell stone fort.",
    'cal': "Late spring — May and June — when the famous wildflowers are at their peak; the limestone is striking year-round.",
    'access': "Terrain is rough and rocky; Poulnabrone dolmen has a short, mostly level path from its car park, while open-country walks are uneven.",
  },
  'story': [
    "When Cromwell's surveyor Edmund Ludlow rode through in 1651 he despaired of the place, reporting a country \"where there is not enough water to drown a man, wood enough to hang him, nor earth enough to bury him.\" He missed the point entirely. The bare rock is a sponge and a hothouse: rain sinks straight through the limestone, warm stone holds the heat, and in the sheltered <em>grikes</em> between the slabs, plants that have no business growing together — spring gentians from the Alps beside dense-flowered orchids from the Mediterranean — flower side by side every May.",
    "People have lived on and worshipped this rock for a very long time. Poulnabrone — <em>Poll na Brón</em>, \"the hole of the sorrows\" — is a portal tomb whose great capstone has balanced here for around 5,800 years; the bones of more than twenty people were buried beneath it. Nearby, Caherconnell stone fort was still occupied into medieval times, and the hills hold hundreds of ring forts, wedge tombs and the ruins of Corcomroe Abbey.",
    "The Burren also hides its water. In wet weather, lakes called <em>turloughs</em> rise up through the ground and then vanish again as the rock drains them away — \"vanishing lakes\" that are found almost nowhere else in the world.",
  ],
  'snippet': "\"Not enough water to drown a man, nor wood to hang him, nor earth to bury him — and yet they have been burying their dead beneath these stones since before the pyramids were built.\"",
  'tours_intro': "The Burren unfolds along MacÉireann's tour between Galway and the Cliffs of Moher, narrated turn-by-turn whichever way you drive it:",
  'routes': [
    ('galway-to-cliffs-of-moher', 'Galway to Cliffs of Moher', '/newimages/burren.webp'),
    ('cliffs-of-moher-to-galway', 'Cliffs of Moher to Galway', '/newimages/cliffs-of-moher.webp'),
  ],
  'related': [
    ('/places/cliffs-of-moher.html', 'Cliffs of Moher', '/newimages/cliffs-of-moher.webp'),
    ('/tours/galway-to-cliffs-of-moher.html', 'Galway to Cliffs of Moher', '/newimages/burren.webp'),
    ('/tours/', 'All audio tours', '/newimages/slea-head.webp'),
  ],
  'faqs': [
    ('What does "the Burren" mean?', "It comes from the Irish word Boireann, meaning \"a rocky place\" or \"great rock\" — an apt name for its vast pavements of bare grey limestone."),
    ('What is there to see and do in the Burren?', "Highlights include the Poulnabrone dolmen, Caherconnell stone fort, Aillwee Cave, the Burren National Park, Corcomroe Abbey and the wildflowers — best explored on a self-drive loop through north Clare."),
    ('When is the best time to visit the Burren?', "Late spring, especially May and June, when the Arctic, Alpine and Mediterranean wildflowers bloom together in the limestone. The landscape itself is striking in every season."),
    ('Is the Burren free to visit?', "Yes — it is free to roam and the Burren National Park is free to enter. A few individual attractions, such as Aillwee Cave and Caherconnell stone fort, charge admission."),
    ('Do I need a phone signal for the audio tour?', "No. Download the tour before you set off and it runs on your phone's GPS, so the stories play automatically even where there is no mobile coverage."),
  ],
 },
]

for p in PLACES:
    build(p)
